// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/match.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type Currency struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{1}
}

func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (m *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(m, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCurrencyResponse struct {
	Currencies           []*Currency `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCurrencyResponse) Reset()         { *m = GetCurrencyResponse{} }
func (m *GetCurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrencyResponse) ProtoMessage()    {}
func (*GetCurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{2}
}

func (m *GetCurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrencyResponse.Unmarshal(m, b)
}
func (m *GetCurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrencyResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrencyResponse.Merge(m, src)
}
func (m *GetCurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrencyResponse.Size(m)
}
func (m *GetCurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrencyResponse proto.InternalMessageInfo

func (m *GetCurrencyResponse) GetCurrencies() []*Currency {
	if m != nil {
		return m.Currencies
	}
	return nil
}

type Symbol struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseCurrency         string   `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency        string   `protobuf:"bytes,3,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	BaseMinAmount        string   `protobuf:"bytes,4,opt,name=base_min_amount,json=baseMinAmount,proto3" json:"base_min_amount,omitempty"`
	BaseIncrement        string   `protobuf:"bytes,5,opt,name=base_increment,json=baseIncrement,proto3" json:"base_increment,omitempty"`
	QuoteIncrement       string   `protobuf:"bytes,6,opt,name=quote_increment,json=quoteIncrement,proto3" json:"quote_increment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Symbol) Reset()         { *m = Symbol{} }
func (m *Symbol) String() string { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()    {}
func (*Symbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{3}
}

func (m *Symbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Symbol.Unmarshal(m, b)
}
func (m *Symbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Symbol.Marshal(b, m, deterministic)
}
func (m *Symbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Symbol.Merge(m, src)
}
func (m *Symbol) XXX_Size() int {
	return xxx_messageInfo_Symbol.Size(m)
}
func (m *Symbol) XXX_DiscardUnknown() {
	xxx_messageInfo_Symbol.DiscardUnknown(m)
}

var xxx_messageInfo_Symbol proto.InternalMessageInfo

func (m *Symbol) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Symbol) GetBaseCurrency() string {
	if m != nil {
		return m.BaseCurrency
	}
	return ""
}

func (m *Symbol) GetQuoteCurrency() string {
	if m != nil {
		return m.QuoteCurrency
	}
	return ""
}

func (m *Symbol) GetBaseMinAmount() string {
	if m != nil {
		return m.BaseMinAmount
	}
	return ""
}

func (m *Symbol) GetBaseIncrement() string {
	if m != nil {
		return m.BaseIncrement
	}
	return ""
}

func (m *Symbol) GetQuoteIncrement() string {
	if m != nil {
		return m.QuoteIncrement
	}
	return ""
}

type GetSymbolsResponse struct {
	Symbols              []*Symbol `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSymbolsResponse) Reset()         { *m = GetSymbolsResponse{} }
func (m *GetSymbolsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSymbolsResponse) ProtoMessage()    {}
func (*GetSymbolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{4}
}

func (m *GetSymbolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSymbolsResponse.Unmarshal(m, b)
}
func (m *GetSymbolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSymbolsResponse.Marshal(b, m, deterministic)
}
func (m *GetSymbolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSymbolsResponse.Merge(m, src)
}
func (m *GetSymbolsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSymbolsResponse.Size(m)
}
func (m *GetSymbolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSymbolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSymbolsResponse proto.InternalMessageInfo

func (m *GetSymbolsResponse) GetSymbols() []*Symbol {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type BalancesRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalancesRequest) Reset()         { *m = BalancesRequest{} }
func (m *BalancesRequest) String() string { return proto.CompactTextString(m) }
func (*BalancesRequest) ProtoMessage()    {}
func (*BalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{5}
}

func (m *BalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalancesRequest.Unmarshal(m, b)
}
func (m *BalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalancesRequest.Marshal(b, m, deterministic)
}
func (m *BalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalancesRequest.Merge(m, src)
}
func (m *BalancesRequest) XXX_Size() int {
	return xxx_messageInfo_BalancesRequest.Size(m)
}
func (m *BalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalancesRequest proto.InternalMessageInfo

func (m *BalancesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BalancesRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Balance struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance              string   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Available            string   `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
	Hold                 string   `protobuf:"bytes,4,opt,name=hold,proto3" json:"hold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{6}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Balance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Balance) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *Balance) GetHold() string {
	if m != nil {
		return m.Hold
	}
	return ""
}

type BalancesResponse struct {
	Balances             []*Balance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BalancesResponse) Reset()         { *m = BalancesResponse{} }
func (m *BalancesResponse) String() string { return proto.CompactTextString(m) }
func (*BalancesResponse) ProtoMessage()    {}
func (*BalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{7}
}

func (m *BalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalancesResponse.Unmarshal(m, b)
}
func (m *BalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalancesResponse.Marshal(b, m, deterministic)
}
func (m *BalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalancesResponse.Merge(m, src)
}
func (m *BalancesResponse) XXX_Size() int {
	return xxx_messageInfo_BalancesResponse.Size(m)
}
func (m *BalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalancesResponse proto.InternalMessageInfo

func (m *BalancesResponse) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type NewOrderRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientOrderId        string   `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Side                 string   `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	Price                string   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderRequest) Reset()         { *m = NewOrderRequest{} }
func (m *NewOrderRequest) String() string { return proto.CompactTextString(m) }
func (*NewOrderRequest) ProtoMessage()    {}
func (*NewOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{8}
}

func (m *NewOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderRequest.Unmarshal(m, b)
}
func (m *NewOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderRequest.Marshal(b, m, deterministic)
}
func (m *NewOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderRequest.Merge(m, src)
}
func (m *NewOrderRequest) XXX_Size() int {
	return xxx_messageInfo_NewOrderRequest.Size(m)
}
func (m *NewOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderRequest proto.InternalMessageInfo

func (m *NewOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NewOrderRequest) GetClientOrderId() string {
	if m != nil {
		return m.ClientOrderId
	}
	return ""
}

func (m *NewOrderRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *NewOrderRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *NewOrderRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *NewOrderRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                string               `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string               `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Symbol               string               `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side                 string               `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	Type                 string               `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DoneAt               *timestamp.Timestamp `protobuf:"bytes,9,opt,name=done_at,json=doneAt,proto3" json:"done_at,omitempty"`
	DoneReason           string               `protobuf:"bytes,10,opt,name=done_reason,json=doneReason,proto3" json:"done_reason,omitempty"`
	FillFees             string               `protobuf:"bytes,11,opt,name=fill_fees,json=fillFees,proto3" json:"fill_fees,omitempty"`
	FilledAmount         string               `protobuf:"bytes,12,opt,name=filled_amount,json=filledAmount,proto3" json:"filled_amount,omitempty"`
	RemainingAmount      string               `protobuf:"bytes,13,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"`
	ExecutedValue        string               `protobuf:"bytes,14,opt,name=executed_value,json=executedValue,proto3" json:"executed_value,omitempty"`
	Status               string               `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{9}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Order) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetDoneAt() *timestamp.Timestamp {
	if m != nil {
		return m.DoneAt
	}
	return nil
}

func (m *Order) GetDoneReason() string {
	if m != nil {
		return m.DoneReason
	}
	return ""
}

func (m *Order) GetFillFees() string {
	if m != nil {
		return m.FillFees
	}
	return ""
}

func (m *Order) GetFilledAmount() string {
	if m != nil {
		return m.FilledAmount
	}
	return ""
}

func (m *Order) GetRemainingAmount() string {
	if m != nil {
		return m.RemainingAmount
	}
	return ""
}

func (m *Order) GetExecutedValue() string {
	if m != nil {
		return m.ExecutedValue
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type NewOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderResponse) Reset()         { *m = NewOrderResponse{} }
func (m *NewOrderResponse) String() string { return proto.CompactTextString(m) }
func (*NewOrderResponse) ProtoMessage()    {}
func (*NewOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{10}
}

func (m *NewOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderResponse.Unmarshal(m, b)
}
func (m *NewOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderResponse.Marshal(b, m, deterministic)
}
func (m *NewOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderResponse.Merge(m, src)
}
func (m *NewOrderResponse) XXX_Size() int {
	return xxx_messageInfo_NewOrderResponse.Size(m)
}
func (m *NewOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderResponse proto.InternalMessageInfo

func (m *NewOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrdersRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdersRequest) Reset()         { *m = OrdersRequest{} }
func (m *OrdersRequest) String() string { return proto.CompactTextString(m) }
func (*OrdersRequest) ProtoMessage()    {}
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{11}
}

func (m *OrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersRequest.Unmarshal(m, b)
}
func (m *OrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersRequest.Marshal(b, m, deterministic)
}
func (m *OrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersRequest.Merge(m, src)
}
func (m *OrdersRequest) XXX_Size() int {
	return xxx_messageInfo_OrdersRequest.Size(m)
}
func (m *OrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersRequest proto.InternalMessageInfo

func (m *OrdersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrdersRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type OrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdersResponse) Reset()         { *m = OrdersResponse{} }
func (m *OrdersResponse) String() string { return proto.CompactTextString(m) }
func (*OrdersResponse) ProtoMessage()    {}
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{12}
}

func (m *OrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersResponse.Unmarshal(m, b)
}
func (m *OrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersResponse.Marshal(b, m, deterministic)
}
func (m *OrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersResponse.Merge(m, src)
}
func (m *OrdersResponse) XXX_Size() int {
	return xxx_messageInfo_OrdersResponse.Size(m)
}
func (m *OrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersResponse proto.InternalMessageInfo

func (m *OrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

// fund management
type UpdateBalanceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBalanceRequest) Reset()         { *m = UpdateBalanceRequest{} }
func (m *UpdateBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBalanceRequest) ProtoMessage()    {}
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{13}
}

func (m *UpdateBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalanceRequest.Unmarshal(m, b)
}
func (m *UpdateBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalanceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalanceRequest.Merge(m, src)
}
func (m *UpdateBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBalanceRequest.Size(m)
}
func (m *UpdateBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalanceRequest proto.InternalMessageInfo

func (m *UpdateBalanceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateBalanceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateBalanceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateBalanceRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *UpdateBalanceRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type UpdateBalanceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBalanceResponse) Reset()         { *m = UpdateBalanceResponse{} }
func (m *UpdateBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBalanceResponse) ProtoMessage()    {}
func (*UpdateBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{14}
}

func (m *UpdateBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBalanceResponse.Unmarshal(m, b)
}
func (m *UpdateBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBalanceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBalanceResponse.Merge(m, src)
}
func (m *UpdateBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBalanceResponse.Size(m)
}
func (m *UpdateBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBalanceResponse proto.InternalMessageInfo

type GetAssetSummaryRequest struct {
	Currencies           []string `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetSummaryRequest) Reset()         { *m = GetAssetSummaryRequest{} }
func (m *GetAssetSummaryRequest) String() string { return proto.CompactTextString(m) }
func (*GetAssetSummaryRequest) ProtoMessage()    {}
func (*GetAssetSummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{15}
}

func (m *GetAssetSummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetSummaryRequest.Unmarshal(m, b)
}
func (m *GetAssetSummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetSummaryRequest.Marshal(b, m, deterministic)
}
func (m *GetAssetSummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetSummaryRequest.Merge(m, src)
}
func (m *GetAssetSummaryRequest) XXX_Size() int {
	return xxx_messageInfo_GetAssetSummaryRequest.Size(m)
}
func (m *GetAssetSummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetSummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetSummaryRequest proto.InternalMessageInfo

func (m *GetAssetSummaryRequest) GetCurrencies() []string {
	if m != nil {
		return m.Currencies
	}
	return nil
}

type Asset struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Total                string   `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	Available            string   `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
	AvailableCount       int64    `protobuf:"varint,4,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	Hold                 string   `protobuf:"bytes,5,opt,name=hold,proto3" json:"hold,omitempty"`
	HoldCount            int64    `protobuf:"varint,6,opt,name=hold_count,json=holdCount,proto3" json:"hold_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{16}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Asset) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *Asset) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *Asset) GetAvailableCount() int64 {
	if m != nil {
		return m.AvailableCount
	}
	return 0
}

func (m *Asset) GetHold() string {
	if m != nil {
		return m.Hold
	}
	return ""
}

func (m *Asset) GetHoldCount() int64 {
	if m != nil {
		return m.HoldCount
	}
	return 0
}

type GetAssetSummaryResponse struct {
	Assets               []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetSummaryResponse) Reset()         { *m = GetAssetSummaryResponse{} }
func (m *GetAssetSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*GetAssetSummaryResponse) ProtoMessage()    {}
func (*GetAssetSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{17}
}

func (m *GetAssetSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetSummaryResponse.Unmarshal(m, b)
}
func (m *GetAssetSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetSummaryResponse.Marshal(b, m, deterministic)
}
func (m *GetAssetSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetSummaryResponse.Merge(m, src)
}
func (m *GetAssetSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_GetAssetSummaryResponse.Size(m)
}
func (m *GetAssetSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetSummaryResponse proto.InternalMessageInfo

func (m *GetAssetSummaryResponse) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

type OrderCancelRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancelRequest) Reset()         { *m = OrderCancelRequest{} }
func (m *OrderCancelRequest) String() string { return proto.CompactTextString(m) }
func (*OrderCancelRequest) ProtoMessage()    {}
func (*OrderCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{18}
}

func (m *OrderCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancelRequest.Unmarshal(m, b)
}
func (m *OrderCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancelRequest.Marshal(b, m, deterministic)
}
func (m *OrderCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancelRequest.Merge(m, src)
}
func (m *OrderCancelRequest) XXX_Size() int {
	return xxx_messageInfo_OrderCancelRequest.Size(m)
}
func (m *OrderCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancelRequest proto.InternalMessageInfo

func (m *OrderCancelRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderCancelRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderCancelRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type OrderCancelResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancelResponse) Reset()         { *m = OrderCancelResponse{} }
func (m *OrderCancelResponse) String() string { return proto.CompactTextString(m) }
func (*OrderCancelResponse) ProtoMessage()    {}
func (*OrderCancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{19}
}

func (m *OrderCancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancelResponse.Unmarshal(m, b)
}
func (m *OrderCancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancelResponse.Marshal(b, m, deterministic)
}
func (m *OrderCancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancelResponse.Merge(m, src)
}
func (m *OrderCancelResponse) XXX_Size() int {
	return xxx_messageInfo_OrderCancelResponse.Size(m)
}
func (m *OrderCancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancelResponse proto.InternalMessageInfo

func (m *OrderCancelResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderBookRequest struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side   int32  `protobuf:"varint,2,opt,name=side,proto3" json:"side,omitempty"`
	// int32 offset = 3;
	Limit                uint64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookRequest) Reset()         { *m = OrderBookRequest{} }
func (m *OrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*OrderBookRequest) ProtoMessage()    {}
func (*OrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{20}
}

func (m *OrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookRequest.Unmarshal(m, b)
}
func (m *OrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookRequest.Marshal(b, m, deterministic)
}
func (m *OrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookRequest.Merge(m, src)
}
func (m *OrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_OrderBookRequest.Size(m)
}
func (m *OrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookRequest proto.InternalMessageInfo

func (m *OrderBookRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderBookRequest) GetSide() int32 {
	if m != nil {
		return m.Side
	}
	return 0
}

func (m *OrderBookRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type OrderBookResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookResponse) Reset()         { *m = OrderBookResponse{} }
func (m *OrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*OrderBookResponse) ProtoMessage()    {}
func (*OrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{21}
}

func (m *OrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookResponse.Unmarshal(m, b)
}
func (m *OrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookResponse.Marshal(b, m, deterministic)
}
func (m *OrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookResponse.Merge(m, src)
}
func (m *OrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_OrderBookResponse.Size(m)
}
func (m *OrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookResponse proto.InternalMessageInfo

func (m *OrderBookResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderBookDepthRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookDepthRequest) Reset()         { *m = OrderBookDepthRequest{} }
func (m *OrderBookDepthRequest) String() string { return proto.CompactTextString(m) }
func (*OrderBookDepthRequest) ProtoMessage()    {}
func (*OrderBookDepthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{22}
}

func (m *OrderBookDepthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookDepthRequest.Unmarshal(m, b)
}
func (m *OrderBookDepthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookDepthRequest.Marshal(b, m, deterministic)
}
func (m *OrderBookDepthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookDepthRequest.Merge(m, src)
}
func (m *OrderBookDepthRequest) XXX_Size() int {
	return xxx_messageInfo_OrderBookDepthRequest.Size(m)
}
func (m *OrderBookDepthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookDepthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookDepthRequest proto.InternalMessageInfo

func (m *OrderBookDepthRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderBookDepthRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type OrderBookData struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string   `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookData) Reset()         { *m = OrderBookData{} }
func (m *OrderBookData) String() string { return proto.CompactTextString(m) }
func (*OrderBookData) ProtoMessage()    {}
func (*OrderBookData) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{23}
}

func (m *OrderBookData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookData.Unmarshal(m, b)
}
func (m *OrderBookData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookData.Marshal(b, m, deterministic)
}
func (m *OrderBookData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookData.Merge(m, src)
}
func (m *OrderBookData) XXX_Size() int {
	return xxx_messageInfo_OrderBookData.Size(m)
}
func (m *OrderBookData) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookData.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookData proto.InternalMessageInfo

func (m *OrderBookData) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrderBookData) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

type OrderBookDepthResponse struct {
	Asks                 []*OrderBookData `protobuf:"bytes,1,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*OrderBookData `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderBookDepthResponse) Reset()         { *m = OrderBookDepthResponse{} }
func (m *OrderBookDepthResponse) String() string { return proto.CompactTextString(m) }
func (*OrderBookDepthResponse) ProtoMessage()    {}
func (*OrderBookDepthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{24}
}

func (m *OrderBookDepthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookDepthResponse.Unmarshal(m, b)
}
func (m *OrderBookDepthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookDepthResponse.Marshal(b, m, deterministic)
}
func (m *OrderBookDepthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookDepthResponse.Merge(m, src)
}
func (m *OrderBookDepthResponse) XXX_Size() int {
	return xxx_messageInfo_OrderBookDepthResponse.Size(m)
}
func (m *OrderBookDepthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookDepthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookDepthResponse proto.InternalMessageInfo

func (m *OrderBookDepthResponse) GetAsks() []*OrderBookData {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBookDepthResponse) GetBids() []*OrderBookData {
	if m != nil {
		return m.Bids
	}
	return nil
}

type OrderDetailRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetailRequest) Reset()         { *m = OrderDetailRequest{} }
func (m *OrderDetailRequest) String() string { return proto.CompactTextString(m) }
func (*OrderDetailRequest) ProtoMessage()    {}
func (*OrderDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{25}
}

func (m *OrderDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailRequest.Unmarshal(m, b)
}
func (m *OrderDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailRequest.Marshal(b, m, deterministic)
}
func (m *OrderDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailRequest.Merge(m, src)
}
func (m *OrderDetailRequest) XXX_Size() int {
	return xxx_messageInfo_OrderDetailRequest.Size(m)
}
func (m *OrderDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailRequest proto.InternalMessageInfo

func (m *OrderDetailRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderDetailRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type OrderDetailResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDetailResponse) Reset()         { *m = OrderDetailResponse{} }
func (m *OrderDetailResponse) String() string { return proto.CompactTextString(m) }
func (*OrderDetailResponse) ProtoMessage()    {}
func (*OrderDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{26}
}

func (m *OrderDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailResponse.Unmarshal(m, b)
}
func (m *OrderDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailResponse.Marshal(b, m, deterministic)
}
func (m *OrderDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailResponse.Merge(m, src)
}
func (m *OrderDetailResponse) XXX_Size() int {
	return xxx_messageInfo_OrderDetailResponse.Size(m)
}
func (m *OrderDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailResponse proto.InternalMessageInfo

func (m *OrderDetailResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetMarketSummaryRequest struct {
	Symbols              []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketSummaryRequest) Reset()         { *m = GetMarketSummaryRequest{} }
func (m *GetMarketSummaryRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketSummaryRequest) ProtoMessage()    {}
func (*GetMarketSummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{27}
}

func (m *GetMarketSummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketSummaryRequest.Unmarshal(m, b)
}
func (m *GetMarketSummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketSummaryRequest.Marshal(b, m, deterministic)
}
func (m *GetMarketSummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketSummaryRequest.Merge(m, src)
}
func (m *GetMarketSummaryRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketSummaryRequest.Size(m)
}
func (m *GetMarketSummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketSummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketSummaryRequest proto.InternalMessageInfo

func (m *GetMarketSummaryRequest) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type Market struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AsksAmount           string   `protobuf:"bytes,2,opt,name=asks_amount,json=asksAmount,proto3" json:"asks_amount,omitempty"`
	AsksCount            int64    `protobuf:"varint,3,opt,name=asks_count,json=asksCount,proto3" json:"asks_count,omitempty"`
	BidsAmount           string   `protobuf:"bytes,4,opt,name=bids_amount,json=bidsAmount,proto3" json:"bids_amount,omitempty"`
	BidsCount            int64    `protobuf:"varint,5,opt,name=bids_count,json=bidsCount,proto3" json:"bids_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{28}
}

func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Market) GetAsksAmount() string {
	if m != nil {
		return m.AsksAmount
	}
	return ""
}

func (m *Market) GetAsksCount() int64 {
	if m != nil {
		return m.AsksCount
	}
	return 0
}

func (m *Market) GetBidsAmount() string {
	if m != nil {
		return m.BidsAmount
	}
	return ""
}

func (m *Market) GetBidsCount() int64 {
	if m != nil {
		return m.BidsCount
	}
	return 0
}

type GetMarketSummaryResponse struct {
	Markets              []*Market `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMarketSummaryResponse) Reset()         { *m = GetMarketSummaryResponse{} }
func (m *GetMarketSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarketSummaryResponse) ProtoMessage()    {}
func (*GetMarketSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c558542612ea92, []int{29}
}

func (m *GetMarketSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketSummaryResponse.Unmarshal(m, b)
}
func (m *GetMarketSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketSummaryResponse.Marshal(b, m, deterministic)
}
func (m *GetMarketSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketSummaryResponse.Merge(m, src)
}
func (m *GetMarketSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarketSummaryResponse.Size(m)
}
func (m *GetMarketSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketSummaryResponse proto.InternalMessageInfo

func (m *GetMarketSummaryResponse) GetMarkets() []*Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "protos.EmptyRequest")
	proto.RegisterType((*Currency)(nil), "protos.Currency")
	proto.RegisterType((*GetCurrencyResponse)(nil), "protos.GetCurrencyResponse")
	proto.RegisterType((*Symbol)(nil), "protos.Symbol")
	proto.RegisterType((*GetSymbolsResponse)(nil), "protos.GetSymbolsResponse")
	proto.RegisterType((*BalancesRequest)(nil), "protos.BalancesRequest")
	proto.RegisterType((*Balance)(nil), "protos.Balance")
	proto.RegisterType((*BalancesResponse)(nil), "protos.BalancesResponse")
	proto.RegisterType((*NewOrderRequest)(nil), "protos.NewOrderRequest")
	proto.RegisterType((*Order)(nil), "protos.Order")
	proto.RegisterType((*NewOrderResponse)(nil), "protos.NewOrderResponse")
	proto.RegisterType((*OrdersRequest)(nil), "protos.OrdersRequest")
	proto.RegisterType((*OrdersResponse)(nil), "protos.OrdersResponse")
	proto.RegisterType((*UpdateBalanceRequest)(nil), "protos.UpdateBalanceRequest")
	proto.RegisterType((*UpdateBalanceResponse)(nil), "protos.UpdateBalanceResponse")
	proto.RegisterType((*GetAssetSummaryRequest)(nil), "protos.GetAssetSummaryRequest")
	proto.RegisterType((*Asset)(nil), "protos.Asset")
	proto.RegisterType((*GetAssetSummaryResponse)(nil), "protos.GetAssetSummaryResponse")
	proto.RegisterType((*OrderCancelRequest)(nil), "protos.OrderCancelRequest")
	proto.RegisterType((*OrderCancelResponse)(nil), "protos.OrderCancelResponse")
	proto.RegisterType((*OrderBookRequest)(nil), "protos.OrderBookRequest")
	proto.RegisterType((*OrderBookResponse)(nil), "protos.OrderBookResponse")
	proto.RegisterType((*OrderBookDepthRequest)(nil), "protos.OrderBookDepthRequest")
	proto.RegisterType((*OrderBookData)(nil), "protos.OrderBookData")
	proto.RegisterType((*OrderBookDepthResponse)(nil), "protos.OrderBookDepthResponse")
	proto.RegisterType((*OrderDetailRequest)(nil), "protos.OrderDetailRequest")
	proto.RegisterType((*OrderDetailResponse)(nil), "protos.OrderDetailResponse")
	proto.RegisterType((*GetMarketSummaryRequest)(nil), "protos.GetMarketSummaryRequest")
	proto.RegisterType((*Market)(nil), "protos.Market")
	proto.RegisterType((*GetMarketSummaryResponse)(nil), "protos.GetMarketSummaryResponse")
}

func init() { proto.RegisterFile("protos/match.proto", fileDescriptor_47c558542612ea92) }

var fileDescriptor_47c558542612ea92 = []byte{
	// 1334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xe9, 0x6e, 0xdb, 0x46,
	0x10, 0x86, 0x2e, 0x4a, 0x1a, 0x45, 0x47, 0x37, 0x8e, 0xcd, 0x30, 0x71, 0x1c, 0x30, 0xcd, 0x85,
	0xa2, 0x72, 0xe1, 0xfc, 0x48, 0x1b, 0xa0, 0x69, 0xe4, 0x1c, 0x46, 0x80, 0xa6, 0x01, 0x98, 0xa4,
	0x3f, 0xfa, 0x47, 0x5d, 0x91, 0x6b, 0x9b, 0x30, 0x0f, 0x99, 0xbb, 0x4c, 0xeb, 0xbe, 0x40, 0x5f,
	0xa3, 0xef, 0xd0, 0x17, 0xe8, 0x83, 0x14, 0x7d, 0x93, 0x02, 0xc5, 0x5e, 0x3c, 0xa5, 0x08, 0xee,
	0x2f, 0x71, 0x66, 0xbf, 0x99, 0x9d, 0x99, 0x9d, 0xf9, 0x76, 0x05, 0x68, 0x99, 0xc4, 0x2c, 0xa6,
	0xfb, 0x21, 0x66, 0xee, 0xe9, 0x54, 0x08, 0xc8, 0x90, 0x3a, 0x6b, 0xef, 0x24, 0x8e, 0x4f, 0x02,
	0xb2, 0x2f, 0xc4, 0x45, 0x7a, 0xbc, 0xcf, 0xfc, 0x90, 0x50, 0x86, 0xc3, 0xa5, 0x04, 0xda, 0x23,
	0xb8, 0xf2, 0x32, 0x5c, 0xb2, 0x0b, 0x87, 0x9c, 0xa7, 0x84, 0x32, 0x7b, 0x0a, 0xbd, 0xe7, 0x69,
	0x92, 0x90, 0xc8, 0xbd, 0x40, 0x23, 0x68, 0xfa, 0x9e, 0xd9, 0xb8, 0xdd, 0x78, 0xd0, 0x77, 0x9a,
	0xbe, 0x87, 0x10, 0xb4, 0x23, 0x1c, 0x12, 0xb3, 0x29, 0x34, 0xe2, 0xdb, 0x3e, 0x82, 0xab, 0x47,
	0x84, 0x69, 0x13, 0x87, 0xd0, 0x65, 0x1c, 0x51, 0x82, 0xbe, 0x02, 0x70, 0xa5, 0xce, 0x27, 0xd4,
	0x6c, 0xdc, 0x6e, 0x3d, 0x18, 0x1c, 0x4c, 0xe4, 0x96, 0x74, 0x9a, 0xa1, 0x0b, 0x18, 0xfb, 0xef,
	0x06, 0x18, 0xef, 0x2e, 0xc2, 0x45, 0x1c, 0xd4, 0xf6, 0xbd, 0x03, 0xc3, 0x05, 0xa6, 0x64, 0xae,
	0xd0, 0x17, 0x2a, 0x80, 0x2b, 0x5c, 0x99, 0x05, 0x7b, 0x17, 0x46, 0xe7, 0x69, 0xcc, 0x0a, 0xa8,
	0x96, 0x40, 0x0d, 0x85, 0x36, 0x83, 0xdd, 0x83, 0xb1, 0xf0, 0x15, 0xfa, 0xd1, 0x1c, 0x87, 0x71,
	0x1a, 0x31, 0xb3, 0x2d, 0x71, 0x5c, 0xfd, 0xc6, 0x8f, 0x66, 0x42, 0xc9, 0xdd, 0x09, 0x9c, 0x1f,
	0xb9, 0x09, 0x09, 0x49, 0xc4, 0xcc, 0x4e, 0x0e, 0x7b, 0xad, 0x95, 0xe8, 0x3e, 0x8c, 0xe5, 0xae,
	0x39, 0xce, 0x10, 0x38, 0x19, 0x4c, 0x06, 0xb4, 0x9f, 0x02, 0x3a, 0x22, 0x4c, 0x26, 0x48, 0xb3,
	0x32, 0x3d, 0x80, 0x2e, 0x95, 0x2a, 0x55, 0xa3, 0x91, 0xae, 0x91, 0x44, 0x3a, 0x7a, 0xd9, 0x7e,
	0x05, 0xe3, 0x43, 0x1c, 0xe0, 0xc8, 0x25, 0x54, 0x1d, 0x15, 0xda, 0x81, 0x6e, 0x4a, 0x49, 0x32,
	0xcf, 0x6a, 0x65, 0x70, 0xf1, 0xb5, 0x87, 0x2c, 0xe8, 0x55, 0x4a, 0x95, 0xc9, 0xf6, 0x39, 0x74,
	0x95, 0x9f, 0x12, 0xac, 0x51, 0x86, 0x21, 0x13, 0xba, 0x0b, 0x09, 0x53, 0x1e, 0xb4, 0x88, 0x6e,
	0x42, 0x1f, 0x7f, 0xc4, 0x7e, 0x80, 0x17, 0x01, 0x51, 0x25, 0xce, 0x15, 0xbc, 0x45, 0x4e, 0xe3,
	0xc0, 0x53, 0x35, 0x15, 0xdf, 0xf6, 0x77, 0x30, 0xc9, 0x43, 0x57, 0x89, 0x7f, 0x01, 0x3d, 0xe5,
	0x50, 0x67, 0x3e, 0xd6, 0x99, 0x2b, 0xac, 0x93, 0x01, 0xec, 0xbf, 0x1a, 0x30, 0xfe, 0x81, 0xfc,
	0xf2, 0x36, 0xf1, 0x48, 0xb2, 0x31, 0xf9, 0x7b, 0x30, 0x76, 0x03, 0x9f, 0x44, 0x6c, 0x1e, 0x73,
	0x3c, 0x07, 0xc8, 0x0c, 0x86, 0x52, 0x2d, 0xbc, 0xbc, 0xf6, 0xd0, 0x36, 0x18, 0xb2, 0xb6, 0x2a,
	0x09, 0x25, 0xf1, 0x0c, 0xd8, 0xc5, 0x92, 0xe8, 0x0c, 0xf8, 0x37, 0xd7, 0x51, 0xdf, 0x23, 0xaa,
	0x05, 0xc4, 0x37, 0xda, 0x82, 0xce, 0x32, 0xf1, 0x5d, 0xa2, 0xce, 0x5b, 0x0a, 0xdc, 0xab, 0xea,
	0xaa, 0xae, 0xf4, 0x2a, 0x25, 0xfb, 0xdf, 0x16, 0x74, 0xc4, 0xce, 0xb5, 0xe6, 0xce, 0xfc, 0x34,
	0x57, 0xfb, 0x69, 0x15, 0xfd, 0x14, 0xa2, 0x6e, 0x57, 0xa3, 0xae, 0x45, 0xa8, 0x33, 0x31, 0x0a,
	0x99, 0x7c, 0x03, 0xe0, 0x26, 0x04, 0x33, 0xe2, 0xcd, 0xb1, 0x8c, 0x71, 0x70, 0x60, 0x4d, 0x25,
	0x49, 0x4c, 0x35, 0x49, 0x4c, 0xdf, 0x6b, 0x92, 0x70, 0xfa, 0x0a, 0x3d, 0x63, 0xdc, 0x34, 0x5d,
	0x7a, 0xda, 0xb4, 0xb7, 0xd9, 0x54, 0xa1, 0x67, 0x0c, 0x3d, 0x82, 0xae, 0x17, 0x47, 0x84, 0xdb,
	0xf5, 0x37, 0xda, 0x19, 0x1c, 0x3a, 0x63, 0x68, 0x0f, 0x06, 0xc2, 0x28, 0x21, 0x98, 0xc6, 0x91,
	0x09, 0x22, 0x0b, 0xe0, 0x2a, 0x47, 0x68, 0xd0, 0x0d, 0xe8, 0x1f, 0xfb, 0x41, 0x30, 0x3f, 0x26,
	0x84, 0x9a, 0x03, 0xd9, 0xc0, 0x5c, 0xf1, 0x8a, 0x10, 0xca, 0x39, 0x83, 0x7f, 0xf3, 0x60, 0x65,
	0x1d, 0xaf, 0x48, 0xce, 0x90, 0x4a, 0x35, 0xe4, 0x0f, 0x61, 0x92, 0x90, 0x10, 0xfb, 0x91, 0x1f,
	0x9d, 0x68, 0xdc, 0x50, 0xe0, 0xc6, 0x99, 0x3e, 0xe7, 0x03, 0xf2, 0x2b, 0x71, 0x53, 0x9e, 0xfe,
	0x47, 0x1c, 0xa4, 0xc4, 0x1c, 0xc9, 0xae, 0xd2, 0xda, 0x1f, 0xb9, 0x52, 0x9c, 0x0f, 0xc3, 0x2c,
	0xa5, 0xe6, 0x58, 0x9d, 0x8f, 0x90, 0xec, 0xc7, 0x30, 0xc9, 0x3b, 0x58, 0xcd, 0xc0, 0x1d, 0xe8,
	0x88, 0x16, 0x15, 0xcd, 0x30, 0x38, 0x18, 0xea, 0x01, 0x90, 0x28, 0xb9, 0x66, 0x3f, 0x83, 0xa1,
	0x90, 0x37, 0x4f, 0x7d, 0xde, 0x1a, 0xcd, 0x62, 0x6b, 0xd8, 0x8f, 0x61, 0xa4, 0x3d, 0xa8, 0x8d,
	0xef, 0x82, 0x21, 0x9c, 0xeb, 0xd1, 0xab, 0xec, 0xac, 0x16, 0xed, 0xdf, 0x1b, 0xb0, 0xf5, 0x41,
	0x9c, 0xa1, 0x1e, 0x49, 0x15, 0xc2, 0x8a, 0x7b, 0x41, 0x34, 0x5a, 0xb3, 0xd0, 0x68, 0x85, 0x30,
	0x5b, 0x6b, 0xc9, 0xa9, 0x5d, 0x61, 0x9d, 0xbc, 0xeb, 0x3b, 0xa5, 0xe9, 0xd9, 0x81, 0x6b, 0x95,
	0x40, 0x64, 0x26, 0xf6, 0xd7, 0xb0, 0x7d, 0x44, 0xd8, 0x8c, 0x52, 0xc2, 0xde, 0xa5, 0x61, 0x88,
	0x13, 0x7d, 0x8f, 0xa1, 0x5b, 0xb5, 0x0b, 0xa8, 0x5f, 0xba, 0x6e, 0xfe, 0x6c, 0x40, 0x47, 0xd8,
	0x7d, 0x92, 0x06, 0xb7, 0xa0, 0xc3, 0x62, 0x86, 0x75, 0x49, 0xa5, 0xb0, 0x81, 0x02, 0xef, 0xc3,
	0x38, 0x13, 0xe6, 0x6e, 0x76, 0xc3, 0xb4, 0x9c, 0x51, 0xa6, 0x7e, 0x2e, 0x5a, 0x4a, 0x73, 0x65,
	0x27, 0xe7, 0x4a, 0xb4, 0x0b, 0xc0, 0x7f, 0x95, 0x9d, 0x21, 0xec, 0xfa, 0x5c, 0x23, 0x4c, 0xec,
	0x67, 0xb0, 0x53, 0xcb, 0x37, 0x3f, 0x54, 0xcc, 0xf5, 0xb5, 0x43, 0x15, 0x68, 0x47, 0x2d, 0xda,
	0x3f, 0x03, 0x12, 0xa7, 0xfc, 0x9c, 0xd7, 0x31, 0xf8, 0xbf, 0x4d, 0x85, 0xae, 0x43, 0x2f, 0xa3,
	0x57, 0x59, 0x81, 0x6e, 0x2c, 0x89, 0xd5, 0x7e, 0x02, 0x57, 0x4b, 0x3b, 0x5c, 0xa6, 0xdb, 0xdf,
	0xc3, 0x44, 0xc8, 0x87, 0x71, 0x7c, 0xa6, 0x63, 0xcb, 0x43, 0x68, 0xac, 0xa4, 0x3c, 0x1e, 0x58,
	0x27, 0x27, 0xe5, 0xc0, 0x0f, 0x7d, 0xc9, 0x9a, 0x6d, 0x47, 0x0a, 0xf6, 0x13, 0xf8, 0xac, 0xe0,
	0xf5, 0x72, 0x43, 0xf0, 0x12, 0xae, 0x65, 0xb6, 0x2f, 0xc8, 0x92, 0x9d, 0x6e, 0x0a, 0x2b, 0x0b,
	0xa1, 0x59, 0x0c, 0x61, 0xa6, 0xc6, 0x58, 0xb8, 0xc1, 0x0c, 0xe7, 0xb4, 0xdf, 0x28, 0xd2, 0xbe,
	0x05, 0xbd, 0xf3, 0x14, 0x47, 0xcc, 0x67, 0xd9, 0xcd, 0xad, 0x65, 0x3b, 0x82, 0xed, 0x6a, 0x24,
	0x2a, 0x95, 0x87, 0xd0, 0xc6, 0xf4, 0x4c, 0x27, 0x72, 0xad, 0x94, 0x88, 0xde, 0xd0, 0x11, 0x10,
	0x0e, 0x5d, 0xf8, 0x1e, 0x35, 0x9b, 0x9f, 0x84, 0x72, 0x88, 0x7d, 0xa4, 0x3a, 0xe5, 0x05, 0x61,
	0xd8, 0x0f, 0x36, 0xa5, 0x5d, 0x6c, 0x88, 0xe6, 0xea, 0x86, 0xd0, 0x8e, 0x2e, 0xd3, 0x10, 0x8f,
	0x44, 0xc3, 0xbf, 0xc1, 0xc9, 0x59, 0x6d, 0xc2, 0xcd, 0xf2, 0xdb, 0xa9, 0x9f, 0xbf, 0x95, 0xfe,
	0x68, 0x80, 0x21, 0x4d, 0xd6, 0x86, 0xbb, 0x07, 0x03, 0x5e, 0x0f, 0x4d, 0xfa, 0x32, 0x62, 0xe0,
	0x2a, 0xc5, 0xf7, 0xbb, 0x20, 0x24, 0x35, 0x88, 0x2d, 0x39, 0x88, 0x5c, 0x23, 0x67, 0x77, 0x0f,
	0x06, 0xbc, 0x48, 0xe5, 0x27, 0x24, 0x70, 0x55, 0x6e, 0x2f, 0x00, 0x6e, 0x46, 0x67, 0x2d, 0xa7,
	0xcf, 0x35, 0x72, 0x90, 0x5f, 0x80, 0x59, 0xcf, 0x2b, 0x7f, 0x14, 0x86, 0x62, 0xa1, 0xf6, 0x28,
	0x94, 0x78, 0x47, 0x2f, 0x1f, 0xfc, 0x63, 0x40, 0xe7, 0x0d, 0x7f, 0xf5, 0xa3, 0x43, 0x18, 0xe6,
	0xcf, 0x70, 0x9f, 0x50, 0xb4, 0xa5, 0x6d, 0x8a, 0xaf, 0x7b, 0xeb, 0x86, 0xd6, 0xae, 0x7a, 0xb3,
	0x3f, 0x05, 0xc8, 0x9f, 0xa8, 0x6b, 0x1c, 0x58, 0x05, 0x07, 0xd5, 0xc7, 0xec, 0xb7, 0xd0, 0xd3,
	0xef, 0x3c, 0xb4, 0x53, 0x79, 0xcd, 0xe9, 0xeb, 0xcb, 0x32, 0xeb, 0x0b, 0xb9, 0xb9, 0xbe, 0x22,
	0x73, 0xf3, 0xca, 0xb3, 0x2f, 0x37, 0xaf, 0xdd, 0xa6, 0x8f, 0xc1, 0x90, 0xd7, 0x1c, 0x2a, 0x77,
	0x75, 0xb6, 0xf3, 0x76, 0x55, 0xad, 0x0c, 0xbf, 0x87, 0x61, 0xe9, 0x72, 0x41, 0x37, 0x35, 0x70,
	0xd5, 0xe5, 0x67, 0xed, 0xae, 0x59, 0x55, 0xde, 0x1c, 0x18, 0x57, 0x18, 0x1a, 0xdd, 0x2a, 0xd4,
	0x6c, 0xc5, 0x55, 0x65, 0xed, 0xad, 0x5d, 0x57, 0x3e, 0x5f, 0xc1, 0xa0, 0xc0, 0xa8, 0xc8, 0x2a,
	0x25, 0x52, 0x22, 0xf2, 0xfc, 0x80, 0x57, 0x51, 0xf0, 0x33, 0xe8, 0x67, 0x83, 0x8e, 0xcc, 0xda,
	0xec, 0x6b, 0x1f, 0xd7, 0x57, 0xac, 0x28, 0x0f, 0x6f, 0xd5, 0x5b, 0x22, 0xe3, 0x20, 0xb4, 0x5b,
	0xa7, 0x90, 0x02, 0x4b, 0x5a, 0xb7, 0xd6, 0x2d, 0x57, 0x52, 0x93, 0xdc, 0x50, 0x49, 0xad, 0xc4,
	0x3c, 0x95, 0xd4, 0x2a, 0x64, 0xf2, 0x01, 0x26, 0xd5, 0x79, 0x42, 0xc5, 0xba, 0xae, 0x62, 0x10,
	0xeb, 0xf6, 0x7a, 0x80, 0x74, 0x7b, 0xf8, 0xf9, 0x4f, 0xf6, 0x89, 0xcf, 0x4e, 0xd3, 0xc5, 0xd4,
	0x8d, 0xc3, 0x7d, 0xef, 0x37, 0x46, 0xdc, 0xd3, 0x7d, 0xea, 0x27, 0x24, 0xfa, 0x72, 0x19, 0x53,
	0xf9, 0xaf, 0x9a, 0x2e, 0xe4, 0x9f, 0xed, 0x47, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x37, 0xa4,
	0xb8, 0x5f, 0x89, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MatchClient is the client API for Match service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MatchClient interface {
	GetCurrencies(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetCurrencyResponse, error)
	GetSymbols(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetSymbolsResponse, error)
	Balances(ctx context.Context, in *BalancesRequest, opts ...grpc.CallOption) (*BalancesResponse, error)
	NewOrder(ctx context.Context, in *NewOrderRequest, opts ...grpc.CallOption) (*NewOrderResponse, error)
	Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error)
	GetAssetSummary(ctx context.Context, in *GetAssetSummaryRequest, opts ...grpc.CallOption) (*GetAssetSummaryResponse, error)
	OrderCancel(ctx context.Context, in *OrderCancelRequest, opts ...grpc.CallOption) (*OrderCancelResponse, error)
	OrderBook(ctx context.Context, in *OrderBookRequest, opts ...grpc.CallOption) (*OrderBookResponse, error)
	OrderBookDepth(ctx context.Context, in *OrderBookDepthRequest, opts ...grpc.CallOption) (*OrderBookDepthResponse, error)
	OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailResponse, error)
	GetMarketSummary(ctx context.Context, in *GetMarketSummaryRequest, opts ...grpc.CallOption) (*GetMarketSummaryResponse, error)
}

type matchClient struct {
	cc *grpc.ClientConn
}

func NewMatchClient(cc *grpc.ClientConn) MatchClient {
	return &matchClient{cc}
}

func (c *matchClient) GetCurrencies(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetCurrencyResponse, error) {
	out := new(GetCurrencyResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/GetCurrencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) GetSymbols(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetSymbolsResponse, error) {
	out := new(GetSymbolsResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/GetSymbols", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) Balances(ctx context.Context, in *BalancesRequest, opts ...grpc.CallOption) (*BalancesResponse, error) {
	out := new(BalancesResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/Balances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) NewOrder(ctx context.Context, in *NewOrderRequest, opts ...grpc.CallOption) (*NewOrderResponse, error) {
	out := new(NewOrderResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/NewOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/Orders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error) {
	out := new(UpdateBalanceResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/UpdateBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) GetAssetSummary(ctx context.Context, in *GetAssetSummaryRequest, opts ...grpc.CallOption) (*GetAssetSummaryResponse, error) {
	out := new(GetAssetSummaryResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/GetAssetSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) OrderCancel(ctx context.Context, in *OrderCancelRequest, opts ...grpc.CallOption) (*OrderCancelResponse, error) {
	out := new(OrderCancelResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/OrderCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) OrderBook(ctx context.Context, in *OrderBookRequest, opts ...grpc.CallOption) (*OrderBookResponse, error) {
	out := new(OrderBookResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/OrderBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) OrderBookDepth(ctx context.Context, in *OrderBookDepthRequest, opts ...grpc.CallOption) (*OrderBookDepthResponse, error) {
	out := new(OrderBookDepthResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/OrderBookDepth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailResponse, error) {
	out := new(OrderDetailResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/OrderDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchClient) GetMarketSummary(ctx context.Context, in *GetMarketSummaryRequest, opts ...grpc.CallOption) (*GetMarketSummaryResponse, error) {
	out := new(GetMarketSummaryResponse)
	err := c.cc.Invoke(ctx, "/protos.Match/GetMarketSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServer is the server API for Match service.
type MatchServer interface {
	GetCurrencies(context.Context, *EmptyRequest) (*GetCurrencyResponse, error)
	GetSymbols(context.Context, *EmptyRequest) (*GetSymbolsResponse, error)
	Balances(context.Context, *BalancesRequest) (*BalancesResponse, error)
	NewOrder(context.Context, *NewOrderRequest) (*NewOrderResponse, error)
	Orders(context.Context, *OrdersRequest) (*OrdersResponse, error)
	UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error)
	GetAssetSummary(context.Context, *GetAssetSummaryRequest) (*GetAssetSummaryResponse, error)
	OrderCancel(context.Context, *OrderCancelRequest) (*OrderCancelResponse, error)
	OrderBook(context.Context, *OrderBookRequest) (*OrderBookResponse, error)
	OrderBookDepth(context.Context, *OrderBookDepthRequest) (*OrderBookDepthResponse, error)
	OrderDetail(context.Context, *OrderDetailRequest) (*OrderDetailResponse, error)
	GetMarketSummary(context.Context, *GetMarketSummaryRequest) (*GetMarketSummaryResponse, error)
}

func RegisterMatchServer(s *grpc.Server, srv MatchServer) {
	s.RegisterService(&_Match_serviceDesc, srv)
}

func _Match_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/GetCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).GetCurrencies(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_GetSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).GetSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/GetSymbols",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).GetSymbols(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_Balances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).Balances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/Balances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).Balances(ctx, req.(*BalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_NewOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).NewOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/NewOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).NewOrder(ctx, req.(*NewOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_Orders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).Orders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/Orders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).Orders(ctx, req.(*OrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/UpdateBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).UpdateBalance(ctx, req.(*UpdateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_GetAssetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).GetAssetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/GetAssetSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).GetAssetSummary(ctx, req.(*GetAssetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_OrderCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).OrderCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/OrderCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).OrderCancel(ctx, req.(*OrderCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_OrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).OrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/OrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).OrderBook(ctx, req.(*OrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_OrderBookDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderBookDepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).OrderBookDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/OrderBookDepth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).OrderBookDepth(ctx, req.(*OrderBookDepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_OrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).OrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/OrderDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).OrderDetail(ctx, req.(*OrderDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Match_GetMarketSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServer).GetMarketSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Match/GetMarketSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServer).GetMarketSummary(ctx, req.(*GetMarketSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Match_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Match",
	HandlerType: (*MatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrencies",
			Handler:    _Match_GetCurrencies_Handler,
		},
		{
			MethodName: "GetSymbols",
			Handler:    _Match_GetSymbols_Handler,
		},
		{
			MethodName: "Balances",
			Handler:    _Match_Balances_Handler,
		},
		{
			MethodName: "NewOrder",
			Handler:    _Match_NewOrder_Handler,
		},
		{
			MethodName: "Orders",
			Handler:    _Match_Orders_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _Match_UpdateBalance_Handler,
		},
		{
			MethodName: "GetAssetSummary",
			Handler:    _Match_GetAssetSummary_Handler,
		},
		{
			MethodName: "OrderCancel",
			Handler:    _Match_OrderCancel_Handler,
		},
		{
			MethodName: "OrderBook",
			Handler:    _Match_OrderBook_Handler,
		},
		{
			MethodName: "OrderBookDepth",
			Handler:    _Match_OrderBookDepth_Handler,
		},
		{
			MethodName: "OrderDetail",
			Handler:    _Match_OrderDetail_Handler,
		},
		{
			MethodName: "GetMarketSummary",
			Handler:    _Match_GetMarketSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/match.proto",
}
