// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/memorystore.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MarketStatusRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Period               int32    `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketStatusRequest) Reset()         { *m = MarketStatusRequest{} }
func (m *MarketStatusRequest) String() string { return proto.CompactTextString(m) }
func (*MarketStatusRequest) ProtoMessage()    {}
func (*MarketStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{0}
}

func (m *MarketStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketStatusRequest.Unmarshal(m, b)
}
func (m *MarketStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketStatusRequest.Marshal(b, m, deterministic)
}
func (m *MarketStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketStatusRequest.Merge(m, src)
}
func (m *MarketStatusRequest) XXX_Size() int {
	return xxx_messageInfo_MarketStatusRequest.Size(m)
}
func (m *MarketStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketStatusRequest proto.InternalMessageInfo

func (m *MarketStatusRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *MarketStatusRequest) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

type MarketStatusReply struct {
	Low                  float64  `protobuf:"fixed64,1,opt,name=low,proto3" json:"low,omitempty"`
	High                 float64  `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	Open                 float64  `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	Close                float64  `protobuf:"fixed64,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume               float64  `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Deal                 float64  `protobuf:"fixed64,6,opt,name=deal,proto3" json:"deal,omitempty"`
	Last                 float64  `protobuf:"fixed64,7,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketStatusReply) Reset()         { *m = MarketStatusReply{} }
func (m *MarketStatusReply) String() string { return proto.CompactTextString(m) }
func (*MarketStatusReply) ProtoMessage()    {}
func (*MarketStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{1}
}

func (m *MarketStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketStatusReply.Unmarshal(m, b)
}
func (m *MarketStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketStatusReply.Marshal(b, m, deterministic)
}
func (m *MarketStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketStatusReply.Merge(m, src)
}
func (m *MarketStatusReply) XXX_Size() int {
	return xxx_messageInfo_MarketStatusReply.Size(m)
}
func (m *MarketStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarketStatusReply proto.InternalMessageInfo

func (m *MarketStatusReply) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *MarketStatusReply) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *MarketStatusReply) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *MarketStatusReply) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *MarketStatusReply) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *MarketStatusReply) GetDeal() float64 {
	if m != nil {
		return m.Deal
	}
	return 0
}

func (m *MarketStatusReply) GetLast() float64 {
	if m != nil {
		return m.Last
	}
	return 0
}

type MarketKlineRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Interval             int64    `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketKlineRequest) Reset()         { *m = MarketKlineRequest{} }
func (m *MarketKlineRequest) String() string { return proto.CompactTextString(m) }
func (*MarketKlineRequest) ProtoMessage()    {}
func (*MarketKlineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{2}
}

func (m *MarketKlineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketKlineRequest.Unmarshal(m, b)
}
func (m *MarketKlineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketKlineRequest.Marshal(b, m, deterministic)
}
func (m *MarketKlineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketKlineRequest.Merge(m, src)
}
func (m *MarketKlineRequest) XXX_Size() int {
	return xxx_messageInfo_MarketKlineRequest.Size(m)
}
func (m *MarketKlineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketKlineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketKlineRequest proto.InternalMessageInfo

func (m *MarketKlineRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *MarketKlineRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *MarketKlineRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *MarketKlineRequest) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type KlineInfo struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Low                  float64  `protobuf:"fixed64,2,opt,name=low,proto3" json:"low,omitempty"`
	High                 float64  `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Open                 float64  `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	Close                float64  `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume               float64  `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Deal                 float64  `protobuf:"fixed64,7,opt,name=deal,proto3" json:"deal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KlineInfo) Reset()         { *m = KlineInfo{} }
func (m *KlineInfo) String() string { return proto.CompactTextString(m) }
func (*KlineInfo) ProtoMessage()    {}
func (*KlineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{3}
}

func (m *KlineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KlineInfo.Unmarshal(m, b)
}
func (m *KlineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KlineInfo.Marshal(b, m, deterministic)
}
func (m *KlineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KlineInfo.Merge(m, src)
}
func (m *KlineInfo) XXX_Size() int {
	return xxx_messageInfo_KlineInfo.Size(m)
}
func (m *KlineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KlineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KlineInfo proto.InternalMessageInfo

func (m *KlineInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *KlineInfo) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *KlineInfo) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *KlineInfo) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *KlineInfo) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *KlineInfo) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *KlineInfo) GetDeal() float64 {
	if m != nil {
		return m.Deal
	}
	return 0
}

type MarketKlineReply struct {
	Items                []*KlineInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MarketKlineReply) Reset()         { *m = MarketKlineReply{} }
func (m *MarketKlineReply) String() string { return proto.CompactTextString(m) }
func (*MarketKlineReply) ProtoMessage()    {}
func (*MarketKlineReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{4}
}

func (m *MarketKlineReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketKlineReply.Unmarshal(m, b)
}
func (m *MarketKlineReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketKlineReply.Marshal(b, m, deterministic)
}
func (m *MarketKlineReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketKlineReply.Merge(m, src)
}
func (m *MarketKlineReply) XXX_Size() int {
	return xxx_messageInfo_MarketKlineReply.Size(m)
}
func (m *MarketKlineReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketKlineReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarketKlineReply proto.InternalMessageInfo

func (m *MarketKlineReply) GetItems() []*KlineInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type MarketDealsRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	LastId               uint64   `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketDealsRequest) Reset()         { *m = MarketDealsRequest{} }
func (m *MarketDealsRequest) String() string { return proto.CompactTextString(m) }
func (*MarketDealsRequest) ProtoMessage()    {}
func (*MarketDealsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{5}
}

func (m *MarketDealsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDealsRequest.Unmarshal(m, b)
}
func (m *MarketDealsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDealsRequest.Marshal(b, m, deterministic)
}
func (m *MarketDealsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDealsRequest.Merge(m, src)
}
func (m *MarketDealsRequest) XXX_Size() int {
	return xxx_messageInfo_MarketDealsRequest.Size(m)
}
func (m *MarketDealsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDealsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDealsRequest proto.InternalMessageInfo

func (m *MarketDealsRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *MarketDealsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MarketDealsRequest) GetLastId() uint64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

type MarketDeal struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Price                string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketDeal) Reset()         { *m = MarketDeal{} }
func (m *MarketDeal) String() string { return proto.CompactTextString(m) }
func (*MarketDeal) ProtoMessage()    {}
func (*MarketDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{6}
}

func (m *MarketDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDeal.Unmarshal(m, b)
}
func (m *MarketDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDeal.Marshal(b, m, deterministic)
}
func (m *MarketDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDeal.Merge(m, src)
}
func (m *MarketDeal) XXX_Size() int {
	return xxx_messageInfo_MarketDeal.Size(m)
}
func (m *MarketDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDeal.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDeal proto.InternalMessageInfo

func (m *MarketDeal) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MarketDeal) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MarketDeal) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MarketDeal) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *MarketDeal) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type MarketDealsReply struct {
	Items                []*MarketDeal `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MarketDealsReply) Reset()         { *m = MarketDealsReply{} }
func (m *MarketDealsReply) String() string { return proto.CompactTextString(m) }
func (*MarketDealsReply) ProtoMessage()    {}
func (*MarketDealsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{7}
}

func (m *MarketDealsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDealsReply.Unmarshal(m, b)
}
func (m *MarketDealsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDealsReply.Marshal(b, m, deterministic)
}
func (m *MarketDealsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDealsReply.Merge(m, src)
}
func (m *MarketDealsReply) XXX_Size() int {
	return xxx_messageInfo_MarketDealsReply.Size(m)
}
func (m *MarketDealsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDealsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDealsReply proto.InternalMessageInfo

func (m *MarketDealsReply) GetItems() []*MarketDeal {
	if m != nil {
		return m.Items
	}
	return nil
}

type MarketLastRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketLastRequest) Reset()         { *m = MarketLastRequest{} }
func (m *MarketLastRequest) String() string { return proto.CompactTextString(m) }
func (*MarketLastRequest) ProtoMessage()    {}
func (*MarketLastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{8}
}

func (m *MarketLastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketLastRequest.Unmarshal(m, b)
}
func (m *MarketLastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketLastRequest.Marshal(b, m, deterministic)
}
func (m *MarketLastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketLastRequest.Merge(m, src)
}
func (m *MarketLastRequest) XXX_Size() int {
	return xxx_messageInfo_MarketLastRequest.Size(m)
}
func (m *MarketLastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketLastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketLastRequest proto.InternalMessageInfo

func (m *MarketLastRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type MarketLastReply struct {
	Last                 float64  `protobuf:"fixed64,1,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketLastReply) Reset()         { *m = MarketLastReply{} }
func (m *MarketLastReply) String() string { return proto.CompactTextString(m) }
func (*MarketLastReply) ProtoMessage()    {}
func (*MarketLastReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{9}
}

func (m *MarketLastReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketLastReply.Unmarshal(m, b)
}
func (m *MarketLastReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketLastReply.Marshal(b, m, deterministic)
}
func (m *MarketLastReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketLastReply.Merge(m, src)
}
func (m *MarketLastReply) XXX_Size() int {
	return xxx_messageInfo_MarketLastReply.Size(m)
}
func (m *MarketLastReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketLastReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarketLastReply proto.InternalMessageInfo

func (m *MarketLastReply) GetLast() float64 {
	if m != nil {
		return m.Last
	}
	return 0
}

type MarketStatusTodayRequest struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketStatusTodayRequest) Reset()         { *m = MarketStatusTodayRequest{} }
func (m *MarketStatusTodayRequest) String() string { return proto.CompactTextString(m) }
func (*MarketStatusTodayRequest) ProtoMessage()    {}
func (*MarketStatusTodayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{10}
}

func (m *MarketStatusTodayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketStatusTodayRequest.Unmarshal(m, b)
}
func (m *MarketStatusTodayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketStatusTodayRequest.Marshal(b, m, deterministic)
}
func (m *MarketStatusTodayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketStatusTodayRequest.Merge(m, src)
}
func (m *MarketStatusTodayRequest) XXX_Size() int {
	return xxx_messageInfo_MarketStatusTodayRequest.Size(m)
}
func (m *MarketStatusTodayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketStatusTodayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketStatusTodayRequest proto.InternalMessageInfo

func (m *MarketStatusTodayRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type MarketStatusTodayReply struct {
	Low                  float64  `protobuf:"fixed64,1,opt,name=low,proto3" json:"low,omitempty"`
	High                 float64  `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	Open                 float64  `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	Last                 float64  `protobuf:"fixed64,4,opt,name=last,proto3" json:"last,omitempty"`
	Volume               float64  `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Deal                 float64  `protobuf:"fixed64,6,opt,name=deal,proto3" json:"deal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketStatusTodayReply) Reset()         { *m = MarketStatusTodayReply{} }
func (m *MarketStatusTodayReply) String() string { return proto.CompactTextString(m) }
func (*MarketStatusTodayReply) ProtoMessage()    {}
func (*MarketStatusTodayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d29c3dbb734b4, []int{11}
}

func (m *MarketStatusTodayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketStatusTodayReply.Unmarshal(m, b)
}
func (m *MarketStatusTodayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketStatusTodayReply.Marshal(b, m, deterministic)
}
func (m *MarketStatusTodayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketStatusTodayReply.Merge(m, src)
}
func (m *MarketStatusTodayReply) XXX_Size() int {
	return xxx_messageInfo_MarketStatusTodayReply.Size(m)
}
func (m *MarketStatusTodayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketStatusTodayReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarketStatusTodayReply proto.InternalMessageInfo

func (m *MarketStatusTodayReply) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *MarketStatusTodayReply) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *MarketStatusTodayReply) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *MarketStatusTodayReply) GetLast() float64 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *MarketStatusTodayReply) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *MarketStatusTodayReply) GetDeal() float64 {
	if m != nil {
		return m.Deal
	}
	return 0
}

func init() {
	proto.RegisterType((*MarketStatusRequest)(nil), "protos.MarketStatusRequest")
	proto.RegisterType((*MarketStatusReply)(nil), "protos.MarketStatusReply")
	proto.RegisterType((*MarketKlineRequest)(nil), "protos.MarketKlineRequest")
	proto.RegisterType((*KlineInfo)(nil), "protos.KlineInfo")
	proto.RegisterType((*MarketKlineReply)(nil), "protos.MarketKlineReply")
	proto.RegisterType((*MarketDealsRequest)(nil), "protos.MarketDealsRequest")
	proto.RegisterType((*MarketDeal)(nil), "protos.MarketDeal")
	proto.RegisterType((*MarketDealsReply)(nil), "protos.MarketDealsReply")
	proto.RegisterType((*MarketLastRequest)(nil), "protos.MarketLastRequest")
	proto.RegisterType((*MarketLastReply)(nil), "protos.MarketLastReply")
	proto.RegisterType((*MarketStatusTodayRequest)(nil), "protos.MarketStatusTodayRequest")
	proto.RegisterType((*MarketStatusTodayReply)(nil), "protos.MarketStatusTodayReply")
}

func init() { proto.RegisterFile("protos/memorystore.proto", fileDescriptor_291d29c3dbb734b4) }

var fileDescriptor_291d29c3dbb734b4 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xc1, 0x6f, 0xd3, 0x3e,
	0x14, 0xc7, 0x97, 0xa6, 0x69, 0x7f, 0x7d, 0xfd, 0x09, 0x36, 0x53, 0x6d, 0x26, 0x48, 0xa8, 0xb2,
	0x40, 0x54, 0x42, 0xb4, 0x52, 0x39, 0xc2, 0x69, 0x62, 0x12, 0x13, 0xec, 0x62, 0x90, 0x90, 0xe0,
	0x80, 0xb2, 0xc6, 0xac, 0x16, 0x4e, 0x1c, 0x62, 0x77, 0xa8, 0x1c, 0xf9, 0x13, 0xb8, 0x72, 0xe4,
	0x1f, 0x45, 0xb6, 0x9b, 0xc6, 0x29, 0x11, 0x05, 0x71, 0x7b, 0xef, 0xd9, 0xf9, 0xfa, 0xf9, 0xe3,
	0xaf, 0x1d, 0xc0, 0x45, 0x29, 0xb5, 0x54, 0xb3, 0x8c, 0x65, 0xb2, 0x5c, 0x2b, 0x2d, 0x4b, 0x36,
	0xb5, 0x25, 0xd4, 0x73, 0x23, 0xe4, 0x0c, 0x6e, 0x5d, 0x24, 0xe5, 0x47, 0xa6, 0x5f, 0xe9, 0x44,
	0xaf, 0x14, 0x65, 0x9f, 0x56, 0x4c, 0x69, 0x74, 0x0c, 0xbd, 0xcc, 0x96, 0x71, 0x30, 0x0e, 0x26,
	0x03, 0xba, 0xc9, 0x4c, 0xbd, 0x60, 0x25, 0x97, 0x29, 0xee, 0x8c, 0x83, 0x49, 0x44, 0x37, 0x19,
	0xf9, 0x11, 0xc0, 0x51, 0x53, 0xa7, 0x10, 0x6b, 0x74, 0x08, 0xa1, 0x90, 0x9f, 0xad, 0x44, 0x40,
	0x4d, 0x88, 0x10, 0x74, 0x97, 0xfc, 0x6a, 0x69, 0xbf, 0x0e, 0xa8, 0x8d, 0x4d, 0x4d, 0x16, 0x2c,
	0xc7, 0xa1, 0xab, 0x99, 0x18, 0x8d, 0x20, 0x5a, 0x08, 0xa9, 0x18, 0xee, 0xda, 0xa2, 0x4b, 0xcc,
	0xea, 0xd7, 0x52, 0xac, 0x32, 0x86, 0x23, 0x5b, 0xde, 0x64, 0x46, 0x21, 0x65, 0x89, 0xc0, 0x3d,
	0xa7, 0x60, 0x62, 0x53, 0x13, 0x89, 0xd2, 0xb8, 0xef, 0x6a, 0x26, 0x26, 0x05, 0x20, 0xd7, 0xe4,
	0x0b, 0xc1, 0x73, 0xb6, 0x6f, 0xaf, 0x23, 0x88, 0x94, 0x4e, 0x4a, 0x6d, 0x9b, 0x0d, 0xa9, 0x4b,
	0xcc, 0x9e, 0x58, 0x9e, 0xda, 0x66, 0x43, 0x6a, 0x42, 0x14, 0xc3, 0x7f, 0x3c, 0xd7, 0xac, 0xbc,
	0x4e, 0x84, 0x6d, 0x37, 0xa4, 0xdb, 0x9c, 0x7c, 0x0f, 0x60, 0x60, 0x17, 0x3b, 0xcf, 0x3f, 0x48,
	0xd3, 0x93, 0xe6, 0x19, 0xb3, 0xeb, 0x84, 0xd4, 0xc6, 0x15, 0xa3, 0xce, 0xaf, 0x8c, 0xc2, 0x16,
	0x46, 0xdd, 0x36, 0x46, 0x51, 0x3b, 0xa3, 0x5e, 0x2b, 0xa3, 0x7e, 0xcd, 0x88, 0x3c, 0x81, 0xc3,
	0x06, 0x0f, 0x73, 0x66, 0x0f, 0x20, 0xe2, 0x9a, 0x65, 0x0a, 0x07, 0xe3, 0x70, 0x32, 0x9c, 0x1f,
	0x39, 0xbf, 0xa8, 0xe9, 0x76, 0x17, 0xd4, 0x8d, 0x93, 0x77, 0x15, 0xcc, 0x67, 0x2c, 0x11, 0xea,
	0x0f, 0x60, 0x0a, 0x9e, 0x71, 0xbd, 0xf1, 0x8d, 0x4b, 0xd0, 0x09, 0xf4, 0xcd, 0xc1, 0xbc, 0xe7,
	0x0e, 0x68, 0x97, 0xf6, 0x4c, 0x7a, 0x9e, 0x92, 0x12, 0xa0, 0x16, 0x37, 0xa2, 0x49, 0x26, 0x57,
	0xf9, 0x56, 0xd4, 0x65, 0xe8, 0x06, 0x74, 0x78, 0xe5, 0xc4, 0x0e, 0x4f, 0xb7, 0x7c, 0x43, 0x8f,
	0xef, 0x08, 0xa2, 0xa2, 0xe4, 0x0b, 0xe7, 0xa4, 0x01, 0x75, 0x89, 0x9d, 0xb9, 0x2e, 0x1c, 0xba,
	0x01, 0xb5, 0x31, 0x79, 0x5a, 0xd1, 0xd8, 0x6c, 0xc8, 0xd0, 0x98, 0x34, 0x69, 0xa0, 0x8a, 0x46,
	0x3d, 0xb1, 0xc2, 0xf1, 0xb0, 0xba, 0x00, 0x2f, 0x13, 0xa5, 0xf7, 0xd0, 0x20, 0xf7, 0xe1, 0xa6,
	0x3f, 0xd9, 0xac, 0x54, 0xf9, 0x35, 0xf0, 0xfc, 0x3a, 0x07, 0xec, 0x5f, 0xaa, 0xd7, 0x32, 0x4d,
	0xd6, 0xfb, 0xa4, 0xbf, 0x05, 0x70, 0xdc, 0xf2, 0xd1, 0xbf, 0x5d, 0xc7, 0xaa, 0xb9, 0x6e, 0xdd,
	0xdc, 0xdf, 0x5c, 0xc6, 0xf9, 0xd7, 0x10, 0x86, 0x17, 0xf5, 0x1b, 0x84, 0x9e, 0xc3, 0xff, 0x7e,
	0x8f, 0xe8, 0x4e, 0x93, 0x6b, 0xe3, 0x2d, 0x8a, 0x6f, 0xb7, 0x0f, 0x16, 0x62, 0x4d, 0x0e, 0xd0,
	0x19, 0x0c, 0x3d, 0x0b, 0xa3, 0xb8, 0x39, 0xd7, 0xbf, 0xe7, 0x31, 0x6e, 0x1d, 0xdb, 0x91, 0xb1,
	0x67, 0xbf, 0x2b, 0xe3, 0x3b, 0x7c, 0x57, 0xa6, 0x36, 0x0b, 0x39, 0x40, 0xa7, 0x95, 0x6d, 0xcd,
	0xb9, 0xa2, 0x9d, 0xc6, 0x3d, 0x63, 0xc4, 0x27, 0x6d, 0x43, 0x4e, 0xe3, 0x4d, 0xf3, 0x25, 0xb5,
	0xe7, 0x87, 0xc6, 0x6d, 0x0c, 0x7c, 0x3f, 0xc4, 0x77, 0x7f, 0x33, 0xc3, 0x0a, 0x9f, 0xde, 0x7b,
	0x4b, 0xae, 0xb8, 0x5e, 0xae, 0x2e, 0xa7, 0x0b, 0x99, 0xcd, 0xd2, 0x2f, 0x9a, 0x2d, 0x96, 0x33,
	0xc5, 0x4b, 0x96, 0x3f, 0x2a, 0xa4, 0x9a, 0xb9, 0xcf, 0x2f, 0xdd, 0x8f, 0xe1, 0xf1, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa4, 0x32, 0x91, 0x5d, 0x3b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemorystoreClient is the client API for Memorystore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemorystoreClient interface {
	MarketStatus(ctx context.Context, in *MarketStatusRequest, opts ...grpc.CallOption) (*MarketStatusReply, error)
	MarketKline(ctx context.Context, in *MarketKlineRequest, opts ...grpc.CallOption) (*MarketKlineReply, error)
	MarketDeals(ctx context.Context, in *MarketDealsRequest, opts ...grpc.CallOption) (*MarketDealsReply, error)
	MarketLast(ctx context.Context, in *MarketLastRequest, opts ...grpc.CallOption) (*MarketLastReply, error)
	MarketStatusToday(ctx context.Context, in *MarketStatusTodayRequest, opts ...grpc.CallOption) (*MarketStatusTodayReply, error)
}

type memorystoreClient struct {
	cc *grpc.ClientConn
}

func NewMemorystoreClient(cc *grpc.ClientConn) MemorystoreClient {
	return &memorystoreClient{cc}
}

func (c *memorystoreClient) MarketStatus(ctx context.Context, in *MarketStatusRequest, opts ...grpc.CallOption) (*MarketStatusReply, error) {
	out := new(MarketStatusReply)
	err := c.cc.Invoke(ctx, "/protos.Memorystore/MarketStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memorystoreClient) MarketKline(ctx context.Context, in *MarketKlineRequest, opts ...grpc.CallOption) (*MarketKlineReply, error) {
	out := new(MarketKlineReply)
	err := c.cc.Invoke(ctx, "/protos.Memorystore/MarketKline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memorystoreClient) MarketDeals(ctx context.Context, in *MarketDealsRequest, opts ...grpc.CallOption) (*MarketDealsReply, error) {
	out := new(MarketDealsReply)
	err := c.cc.Invoke(ctx, "/protos.Memorystore/MarketDeals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memorystoreClient) MarketLast(ctx context.Context, in *MarketLastRequest, opts ...grpc.CallOption) (*MarketLastReply, error) {
	out := new(MarketLastReply)
	err := c.cc.Invoke(ctx, "/protos.Memorystore/MarketLast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memorystoreClient) MarketStatusToday(ctx context.Context, in *MarketStatusTodayRequest, opts ...grpc.CallOption) (*MarketStatusTodayReply, error) {
	out := new(MarketStatusTodayReply)
	err := c.cc.Invoke(ctx, "/protos.Memorystore/MarketStatusToday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemorystoreServer is the server API for Memorystore service.
type MemorystoreServer interface {
	MarketStatus(context.Context, *MarketStatusRequest) (*MarketStatusReply, error)
	MarketKline(context.Context, *MarketKlineRequest) (*MarketKlineReply, error)
	MarketDeals(context.Context, *MarketDealsRequest) (*MarketDealsReply, error)
	MarketLast(context.Context, *MarketLastRequest) (*MarketLastReply, error)
	MarketStatusToday(context.Context, *MarketStatusTodayRequest) (*MarketStatusTodayReply, error)
}

func RegisterMemorystoreServer(s *grpc.Server, srv MemorystoreServer) {
	s.RegisterService(&_Memorystore_serviceDesc, srv)
}

func _Memorystore_MarketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemorystoreServer).MarketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Memorystore/MarketStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemorystoreServer).MarketStatus(ctx, req.(*MarketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Memorystore_MarketKline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketKlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemorystoreServer).MarketKline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Memorystore/MarketKline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemorystoreServer).MarketKline(ctx, req.(*MarketKlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Memorystore_MarketDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemorystoreServer).MarketDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Memorystore/MarketDeals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemorystoreServer).MarketDeals(ctx, req.(*MarketDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Memorystore_MarketLast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketLastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemorystoreServer).MarketLast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Memorystore/MarketLast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemorystoreServer).MarketLast(ctx, req.(*MarketLastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Memorystore_MarketStatusToday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketStatusTodayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemorystoreServer).MarketStatusToday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Memorystore/MarketStatusToday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemorystoreServer).MarketStatusToday(ctx, req.(*MarketStatusTodayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Memorystore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Memorystore",
	HandlerType: (*MemorystoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MarketStatus",
			Handler:    _Memorystore_MarketStatus_Handler,
		},
		{
			MethodName: "MarketKline",
			Handler:    _Memorystore_MarketKline_Handler,
		},
		{
			MethodName: "MarketDeals",
			Handler:    _Memorystore_MarketDeals_Handler,
		},
		{
			MethodName: "MarketLast",
			Handler:    _Memorystore_MarketLast_Handler,
		},
		{
			MethodName: "MarketStatusToday",
			Handler:    _Memorystore_MarketStatusToday_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/memorystore.proto",
}
