// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/sql.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransfersRequest struct {
	UserId               string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency             string               `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Type                 string               `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Since                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=until,proto3" json:"until,omitempty"`
	Limit                int32                `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransfersRequest) Reset()         { *m = TransfersRequest{} }
func (m *TransfersRequest) String() string { return proto.CompactTextString(m) }
func (*TransfersRequest) ProtoMessage()    {}
func (*TransfersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{0}
}

func (m *TransfersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransfersRequest.Unmarshal(m, b)
}
func (m *TransfersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransfersRequest.Marshal(b, m, deterministic)
}
func (m *TransfersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransfersRequest.Merge(m, src)
}
func (m *TransfersRequest) XXX_Size() int {
	return xxx_messageInfo_TransfersRequest.Size(m)
}
func (m *TransfersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransfersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransfersRequest proto.InternalMessageInfo

func (m *TransfersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TransfersRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *TransfersRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TransfersRequest) GetSince() *timestamp.Timestamp {
	if m != nil {
		return m.Since
	}
	return nil
}

func (m *TransfersRequest) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

func (m *TransfersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Transfer struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Currency             string               `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Type                 string               `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Amount               string               `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               string               `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{1}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transfer) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Transfer) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Transfer) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Transfer) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Transfer) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Transfer) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type TransfersResponse struct {
	Transfers            []*Transfer `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransfersResponse) Reset()         { *m = TransfersResponse{} }
func (m *TransfersResponse) String() string { return proto.CompactTextString(m) }
func (*TransfersResponse) ProtoMessage()    {}
func (*TransfersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{2}
}

func (m *TransfersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransfersResponse.Unmarshal(m, b)
}
func (m *TransfersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransfersResponse.Marshal(b, m, deterministic)
}
func (m *TransfersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransfersResponse.Merge(m, src)
}
func (m *TransfersResponse) XXX_Size() int {
	return xxx_messageInfo_TransfersResponse.Size(m)
}
func (m *TransfersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransfersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransfersResponse proto.InternalMessageInfo

func (m *TransfersResponse) GetTransfers() []*Transfer {
	if m != nil {
		return m.Transfers
	}
	return nil
}

type GetOrderHistoryRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Offset               int32    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Side                 int32    `protobuf:"varint,7,opt,name=side,proto3" json:"side,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderHistoryRequest) Reset()         { *m = GetOrderHistoryRequest{} }
func (m *GetOrderHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderHistoryRequest) ProtoMessage()    {}
func (*GetOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{3}
}

func (m *GetOrderHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderHistoryRequest.Unmarshal(m, b)
}
func (m *GetOrderHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderHistoryRequest.Merge(m, src)
}
func (m *GetOrderHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderHistoryRequest.Size(m)
}
func (m *GetOrderHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderHistoryRequest proto.InternalMessageInfo

func (m *GetOrderHistoryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetOrderHistoryRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *GetOrderHistoryRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetOrderHistoryRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *GetOrderHistoryRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetOrderHistoryRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetOrderHistoryRequest) GetSide() int32 {
	if m != nil {
		return m.Side
	}
	return 0
}

type OrderHistory struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ctime                int64    `protobuf:"varint,2,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Ftime                int64    `protobuf:"varint,3,opt,name=ftime,proto3" json:"ftime,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Market               string   `protobuf:"bytes,5,opt,name=market,proto3" json:"market,omitempty"`
	Source               string   `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Type                 uint32   `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	Side                 uint32   `protobuf:"varint,8,opt,name=side,proto3" json:"side,omitempty"`
	Price                string   `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,10,opt,name=amount,proto3" json:"amount,omitempty"`
	TakerFee             string   `protobuf:"bytes,11,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	MakerFee             string   `protobuf:"bytes,12,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	DealStock            string   `protobuf:"bytes,13,opt,name=deal_stock,json=dealStock,proto3" json:"deal_stock,omitempty"`
	DealMoney            string   `protobuf:"bytes,14,opt,name=deal_money,json=dealMoney,proto3" json:"deal_money,omitempty"`
	DealFee              string   `protobuf:"bytes,15,opt,name=deal_fee,json=dealFee,proto3" json:"deal_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderHistory) Reset()         { *m = OrderHistory{} }
func (m *OrderHistory) String() string { return proto.CompactTextString(m) }
func (*OrderHistory) ProtoMessage()    {}
func (*OrderHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{4}
}

func (m *OrderHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderHistory.Unmarshal(m, b)
}
func (m *OrderHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderHistory.Marshal(b, m, deterministic)
}
func (m *OrderHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderHistory.Merge(m, src)
}
func (m *OrderHistory) XXX_Size() int {
	return xxx_messageInfo_OrderHistory.Size(m)
}
func (m *OrderHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderHistory.DiscardUnknown(m)
}

var xxx_messageInfo_OrderHistory proto.InternalMessageInfo

func (m *OrderHistory) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderHistory) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *OrderHistory) GetFtime() int64 {
	if m != nil {
		return m.Ftime
	}
	return 0
}

func (m *OrderHistory) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *OrderHistory) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *OrderHistory) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *OrderHistory) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *OrderHistory) GetSide() uint32 {
	if m != nil {
		return m.Side
	}
	return 0
}

func (m *OrderHistory) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrderHistory) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *OrderHistory) GetTakerFee() string {
	if m != nil {
		return m.TakerFee
	}
	return ""
}

func (m *OrderHistory) GetMakerFee() string {
	if m != nil {
		return m.MakerFee
	}
	return ""
}

func (m *OrderHistory) GetDealStock() string {
	if m != nil {
		return m.DealStock
	}
	return ""
}

func (m *OrderHistory) GetDealMoney() string {
	if m != nil {
		return m.DealMoney
	}
	return ""
}

func (m *OrderHistory) GetDealFee() string {
	if m != nil {
		return m.DealFee
	}
	return ""
}

type GetOrderHistoryReply struct {
	Items                []*OrderHistory `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetOrderHistoryReply) Reset()         { *m = GetOrderHistoryReply{} }
func (m *GetOrderHistoryReply) String() string { return proto.CompactTextString(m) }
func (*GetOrderHistoryReply) ProtoMessage()    {}
func (*GetOrderHistoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{5}
}

func (m *GetOrderHistoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderHistoryReply.Unmarshal(m, b)
}
func (m *GetOrderHistoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderHistoryReply.Marshal(b, m, deterministic)
}
func (m *GetOrderHistoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderHistoryReply.Merge(m, src)
}
func (m *GetOrderHistoryReply) XXX_Size() int {
	return xxx_messageInfo_GetOrderHistoryReply.Size(m)
}
func (m *GetOrderHistoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderHistoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderHistoryReply proto.InternalMessageInfo

func (m *GetOrderHistoryReply) GetItems() []*OrderHistory {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetOrderDealsRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderDealsRequest) Reset()         { *m = GetOrderDealsRequest{} }
func (m *GetOrderDealsRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderDealsRequest) ProtoMessage()    {}
func (*GetOrderDealsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{6}
}

func (m *GetOrderDealsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderDealsRequest.Unmarshal(m, b)
}
func (m *GetOrderDealsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderDealsRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderDealsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderDealsRequest.Merge(m, src)
}
func (m *GetOrderDealsRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderDealsRequest.Size(m)
}
func (m *GetOrderDealsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderDealsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderDealsRequest proto.InternalMessageInfo

func (m *GetOrderDealsRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetOrderDealsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetOrderDealsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type OrderDeals struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Role                 int32    `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Deal                 string   `protobuf:"bytes,7,opt,name=deal,proto3" json:"deal,omitempty"`
	Fee                  string   `protobuf:"bytes,8,opt,name=fee,proto3" json:"fee,omitempty"`
	DealOrderId          uint64   `protobuf:"varint,9,opt,name=deal_order_id,json=dealOrderId,proto3" json:"deal_order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderDeals) Reset()         { *m = OrderDeals{} }
func (m *OrderDeals) String() string { return proto.CompactTextString(m) }
func (*OrderDeals) ProtoMessage()    {}
func (*OrderDeals) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{7}
}

func (m *OrderDeals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDeals.Unmarshal(m, b)
}
func (m *OrderDeals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDeals.Marshal(b, m, deterministic)
}
func (m *OrderDeals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDeals.Merge(m, src)
}
func (m *OrderDeals) XXX_Size() int {
	return xxx_messageInfo_OrderDeals.Size(m)
}
func (m *OrderDeals) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDeals.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDeals proto.InternalMessageInfo

func (m *OrderDeals) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *OrderDeals) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *OrderDeals) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderDeals) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *OrderDeals) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrderDeals) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *OrderDeals) GetDeal() string {
	if m != nil {
		return m.Deal
	}
	return ""
}

func (m *OrderDeals) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *OrderDeals) GetDealOrderId() uint64 {
	if m != nil {
		return m.DealOrderId
	}
	return 0
}

type GetOrderDealsReply struct {
	Items                []*OrderDeals `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetOrderDealsReply) Reset()         { *m = GetOrderDealsReply{} }
func (m *GetOrderDealsReply) String() string { return proto.CompactTextString(m) }
func (*GetOrderDealsReply) ProtoMessage()    {}
func (*GetOrderDealsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{8}
}

func (m *GetOrderDealsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderDealsReply.Unmarshal(m, b)
}
func (m *GetOrderDealsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderDealsReply.Marshal(b, m, deterministic)
}
func (m *GetOrderDealsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderDealsReply.Merge(m, src)
}
func (m *GetOrderDealsReply) XXX_Size() int {
	return xxx_messageInfo_GetOrderDealsReply.Size(m)
}
func (m *GetOrderDealsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderDealsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderDealsReply proto.InternalMessageInfo

func (m *GetOrderDealsReply) GetItems() []*OrderDeals {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetOrderDetailFinishedRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderDetailFinishedRequest) Reset()         { *m = GetOrderDetailFinishedRequest{} }
func (m *GetOrderDetailFinishedRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderDetailFinishedRequest) ProtoMessage()    {}
func (*GetOrderDetailFinishedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{9}
}

func (m *GetOrderDetailFinishedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderDetailFinishedRequest.Unmarshal(m, b)
}
func (m *GetOrderDetailFinishedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderDetailFinishedRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderDetailFinishedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderDetailFinishedRequest.Merge(m, src)
}
func (m *GetOrderDetailFinishedRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderDetailFinishedRequest.Size(m)
}
func (m *GetOrderDetailFinishedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderDetailFinishedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderDetailFinishedRequest proto.InternalMessageInfo

func (m *GetOrderDetailFinishedRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetOrderDetailFinishedReply struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ctime                int64    `protobuf:"varint,2,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Ftime                int64    `protobuf:"varint,3,opt,name=ftime,proto3" json:"ftime,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Market               string   `protobuf:"bytes,5,opt,name=market,proto3" json:"market,omitempty"`
	Source               string   `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Type                 uint32   `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	Side                 uint32   `protobuf:"varint,8,opt,name=side,proto3" json:"side,omitempty"`
	Price                string   `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,10,opt,name=amount,proto3" json:"amount,omitempty"`
	TakerFee             string   `protobuf:"bytes,11,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	MakerFee             string   `protobuf:"bytes,12,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	DealStock            string   `protobuf:"bytes,13,opt,name=deal_stock,json=dealStock,proto3" json:"deal_stock,omitempty"`
	DealMoney            string   `protobuf:"bytes,14,opt,name=deal_money,json=dealMoney,proto3" json:"deal_money,omitempty"`
	DealFee              string   `protobuf:"bytes,15,opt,name=deal_fee,json=dealFee,proto3" json:"deal_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderDetailFinishedReply) Reset()         { *m = GetOrderDetailFinishedReply{} }
func (m *GetOrderDetailFinishedReply) String() string { return proto.CompactTextString(m) }
func (*GetOrderDetailFinishedReply) ProtoMessage()    {}
func (*GetOrderDetailFinishedReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{10}
}

func (m *GetOrderDetailFinishedReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderDetailFinishedReply.Unmarshal(m, b)
}
func (m *GetOrderDetailFinishedReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderDetailFinishedReply.Marshal(b, m, deterministic)
}
func (m *GetOrderDetailFinishedReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderDetailFinishedReply.Merge(m, src)
}
func (m *GetOrderDetailFinishedReply) XXX_Size() int {
	return xxx_messageInfo_GetOrderDetailFinishedReply.Size(m)
}
func (m *GetOrderDetailFinishedReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderDetailFinishedReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderDetailFinishedReply proto.InternalMessageInfo

func (m *GetOrderDetailFinishedReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetOrderDetailFinishedReply) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *GetOrderDetailFinishedReply) GetFtime() int64 {
	if m != nil {
		return m.Ftime
	}
	return 0
}

func (m *GetOrderDetailFinishedReply) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetOrderDetailFinishedReply) GetSide() uint32 {
	if m != nil {
		return m.Side
	}
	return 0
}

func (m *GetOrderDetailFinishedReply) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetTakerFee() string {
	if m != nil {
		return m.TakerFee
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetMakerFee() string {
	if m != nil {
		return m.MakerFee
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetDealStock() string {
	if m != nil {
		return m.DealStock
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetDealMoney() string {
	if m != nil {
		return m.DealMoney
	}
	return ""
}

func (m *GetOrderDetailFinishedReply) GetDealFee() string {
	if m != nil {
		return m.DealFee
	}
	return ""
}

type GetMarketUserDealsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarketUserDealsRequest) Reset()         { *m = GetMarketUserDealsRequest{} }
func (m *GetMarketUserDealsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarketUserDealsRequest) ProtoMessage()    {}
func (*GetMarketUserDealsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{11}
}

func (m *GetMarketUserDealsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketUserDealsRequest.Unmarshal(m, b)
}
func (m *GetMarketUserDealsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketUserDealsRequest.Marshal(b, m, deterministic)
}
func (m *GetMarketUserDealsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketUserDealsRequest.Merge(m, src)
}
func (m *GetMarketUserDealsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarketUserDealsRequest.Size(m)
}
func (m *GetMarketUserDealsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketUserDealsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketUserDealsRequest proto.InternalMessageInfo

func (m *GetMarketUserDealsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetMarketUserDealsRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *GetMarketUserDealsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetMarketUserDealsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type MarketUserDeals struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Side                 int32    `protobuf:"varint,4,opt,name=side,proto3" json:"side,omitempty"`
	Role                 int32    `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	Price                string   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Deal                 string   `protobuf:"bytes,8,opt,name=deal,proto3" json:"deal,omitempty"`
	Fee                  string   `protobuf:"bytes,9,opt,name=fee,proto3" json:"fee,omitempty"`
	DealOrderId          uint64   `protobuf:"varint,10,opt,name=deal_order_id,json=dealOrderId,proto3" json:"deal_order_id,omitempty"`
	Market               string   `protobuf:"bytes,11,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketUserDeals) Reset()         { *m = MarketUserDeals{} }
func (m *MarketUserDeals) String() string { return proto.CompactTextString(m) }
func (*MarketUserDeals) ProtoMessage()    {}
func (*MarketUserDeals) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{12}
}

func (m *MarketUserDeals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketUserDeals.Unmarshal(m, b)
}
func (m *MarketUserDeals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketUserDeals.Marshal(b, m, deterministic)
}
func (m *MarketUserDeals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketUserDeals.Merge(m, src)
}
func (m *MarketUserDeals) XXX_Size() int {
	return xxx_messageInfo_MarketUserDeals.Size(m)
}
func (m *MarketUserDeals) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketUserDeals.DiscardUnknown(m)
}

var xxx_messageInfo_MarketUserDeals proto.InternalMessageInfo

func (m *MarketUserDeals) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MarketUserDeals) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *MarketUserDeals) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MarketUserDeals) GetSide() int32 {
	if m != nil {
		return m.Side
	}
	return 0
}

func (m *MarketUserDeals) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *MarketUserDeals) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *MarketUserDeals) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MarketUserDeals) GetDeal() string {
	if m != nil {
		return m.Deal
	}
	return ""
}

func (m *MarketUserDeals) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *MarketUserDeals) GetDealOrderId() uint64 {
	if m != nil {
		return m.DealOrderId
	}
	return 0
}

func (m *MarketUserDeals) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

type GetMarketUserDealsReply struct {
	Items                []*MarketUserDeals `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetMarketUserDealsReply) Reset()         { *m = GetMarketUserDealsReply{} }
func (m *GetMarketUserDealsReply) String() string { return proto.CompactTextString(m) }
func (*GetMarketUserDealsReply) ProtoMessage()    {}
func (*GetMarketUserDealsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1fb125921f7262, []int{13}
}

func (m *GetMarketUserDealsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarketUserDealsReply.Unmarshal(m, b)
}
func (m *GetMarketUserDealsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarketUserDealsReply.Marshal(b, m, deterministic)
}
func (m *GetMarketUserDealsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarketUserDealsReply.Merge(m, src)
}
func (m *GetMarketUserDealsReply) XXX_Size() int {
	return xxx_messageInfo_GetMarketUserDealsReply.Size(m)
}
func (m *GetMarketUserDealsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarketUserDealsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarketUserDealsReply proto.InternalMessageInfo

func (m *GetMarketUserDealsReply) GetItems() []*MarketUserDeals {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*TransfersRequest)(nil), "protos.TransfersRequest")
	proto.RegisterType((*Transfer)(nil), "protos.Transfer")
	proto.RegisterType((*TransfersResponse)(nil), "protos.TransfersResponse")
	proto.RegisterType((*GetOrderHistoryRequest)(nil), "protos.GetOrderHistoryRequest")
	proto.RegisterType((*OrderHistory)(nil), "protos.OrderHistory")
	proto.RegisterType((*GetOrderHistoryReply)(nil), "protos.GetOrderHistoryReply")
	proto.RegisterType((*GetOrderDealsRequest)(nil), "protos.GetOrderDealsRequest")
	proto.RegisterType((*OrderDeals)(nil), "protos.OrderDeals")
	proto.RegisterType((*GetOrderDealsReply)(nil), "protos.GetOrderDealsReply")
	proto.RegisterType((*GetOrderDetailFinishedRequest)(nil), "protos.GetOrderDetailFinishedRequest")
	proto.RegisterType((*GetOrderDetailFinishedReply)(nil), "protos.GetOrderDetailFinishedReply")
	proto.RegisterType((*GetMarketUserDealsRequest)(nil), "protos.GetMarketUserDealsRequest")
	proto.RegisterType((*MarketUserDeals)(nil), "protos.MarketUserDeals")
	proto.RegisterType((*GetMarketUserDealsReply)(nil), "protos.GetMarketUserDealsReply")
}

func init() { proto.RegisterFile("protos/sql.proto", fileDescriptor_5d1fb125921f7262) }

var fileDescriptor_5d1fb125921f7262 = []byte{
	// 952 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4d, 0x6f, 0xe4, 0x44,
	0x13, 0x7e, 0x3d, 0x1e, 0xcf, 0x8c, 0x6b, 0x36, 0x9b, 0xbc, 0xad, 0x28, 0x71, 0xbc, 0x84, 0x0d,
	0x06, 0xa4, 0x11, 0xd2, 0xce, 0xa0, 0x70, 0x82, 0x03, 0x62, 0x17, 0x94, 0x5d, 0x84, 0x56, 0x2b,
	0xbc, 0xcb, 0x65, 0x2f, 0x23, 0xc7, 0xae, 0x49, 0xac, 0xf8, 0x2b, 0xee, 0xf6, 0x61, 0xf6, 0xc6,
	0x85, 0x3f, 0xc3, 0xef, 0xe0, 0xce, 0x85, 0xff, 0xc1, 0x8d, 0x2b, 0xea, 0x6a, 0x7f, 0xce, 0x38,
	0x19, 0xad, 0x90, 0x38, 0x71, 0xeb, 0xfa, 0xea, 0xae, 0x7a, 0xea, 0xa9, 0xb2, 0xe1, 0x20, 0xcb,
	0x53, 0x91, 0xf2, 0x05, 0xbf, 0x8d, 0xe6, 0x74, 0x64, 0x23, 0xa5, 0xb1, 0x1f, 0x5f, 0xa5, 0xe9,
	0x55, 0x84, 0x0b, 0x12, 0x2f, 0x8b, 0xd5, 0x42, 0x84, 0x31, 0x72, 0xe1, 0xc5, 0x99, 0x72, 0x74,
	0xfe, 0xd0, 0xe0, 0xe0, 0x4d, 0xee, 0x25, 0x7c, 0x85, 0x39, 0x77, 0xf1, 0xb6, 0x40, 0x2e, 0xd8,
	0x31, 0x8c, 0x0b, 0x8e, 0xf9, 0x32, 0x0c, 0x2c, 0xed, 0x4c, 0x9b, 0x99, 0xee, 0x48, 0x8a, 0xdf,
	0x07, 0xcc, 0x86, 0x89, 0x5f, 0xe4, 0x39, 0x26, 0xfe, 0xda, 0x1a, 0x90, 0xa5, 0x96, 0x19, 0x83,
	0xa1, 0x58, 0x67, 0x68, 0xe9, 0xa4, 0xa7, 0x33, 0xfb, 0x1c, 0x0c, 0x1e, 0x26, 0x3e, 0x5a, 0xc3,
	0x33, 0x6d, 0x36, 0x3d, 0xb7, 0xe7, 0x2a, 0x9d, 0x79, 0x95, 0xce, 0xfc, 0x4d, 0x95, 0x8e, 0xab,
	0x1c, 0x65, 0x44, 0x91, 0x88, 0x30, 0xb2, 0x8c, 0xdd, 0x11, 0xe4, 0xc8, 0x0e, 0xc1, 0x88, 0xc2,
	0x38, 0x14, 0xd6, 0xe8, 0x4c, 0x9b, 0x19, 0xae, 0x12, 0x9c, 0x3f, 0x35, 0x98, 0x54, 0x75, 0xb1,
	0x87, 0x30, 0xa8, 0x4b, 0x19, 0x84, 0xef, 0x5f, 0xc6, 0x11, 0x8c, 0xbc, 0x38, 0x2d, 0x12, 0x41,
	0x75, 0x98, 0x6e, 0x29, 0x49, 0x3d, 0x17, 0x9e, 0x28, 0x38, 0x65, 0x6b, 0xba, 0xa5, 0xc4, 0xbe,
	0x04, 0xf0, 0x73, 0xf4, 0x04, 0x06, 0x4b, 0x4f, 0xe5, 0x75, 0x7f, 0x25, 0x66, 0xe9, 0xfd, 0x54,
	0xc8, 0xd0, 0x22, 0x0b, 0xaa, 0xd0, 0xf1, 0xee, 0xd0, 0xd2, 0xfb, 0xa9, 0x70, 0xbe, 0x85, 0xff,
	0xb7, 0x3a, 0xc9, 0xb3, 0x34, 0xe1, 0xc8, 0xe6, 0x60, 0x8a, 0x4a, 0x69, 0x69, 0x67, 0xfa, 0x6c,
	0x7a, 0x7e, 0xa0, 0xee, 0xe1, 0xf3, 0xca, 0xdb, 0x6d, 0x5c, 0x9c, 0xdf, 0x34, 0x38, 0x7a, 0x8e,
	0xe2, 0x55, 0x1e, 0x60, 0xfe, 0x22, 0xe4, 0x22, 0xcd, 0xd7, 0x3b, 0x59, 0x71, 0x04, 0xa3, 0xd8,
	0xcb, 0x6f, 0x50, 0x94, 0x60, 0x96, 0x12, 0x3b, 0x05, 0xe0, 0xc2, 0xcb, 0xc5, 0x52, 0x92, 0x8e,
	0x00, 0xd5, 0x5d, 0x93, 0x34, 0x32, 0x7f, 0x76, 0x02, 0x13, 0x4c, 0x02, 0x65, 0x1c, 0x92, 0x71,
	0x8c, 0x49, 0x40, 0xa6, 0x23, 0x18, 0xa5, 0xab, 0x15, 0x47, 0x41, 0xc0, 0x1a, 0x6e, 0x29, 0xf5,
	0xf7, 0x5a, 0xb6, 0x8c, 0x87, 0x01, 0x12, 0x5a, 0x86, 0x4b, 0x67, 0xe7, 0xaf, 0x01, 0x3c, 0x68,
	0x17, 0xd1, 0xe2, 0xc0, 0x90, 0x38, 0x70, 0x08, 0x86, 0x4f, 0x4f, 0x0f, 0xe8, 0x69, 0x25, 0x48,
	0xed, 0xaa, 0x95, 0xad, 0x12, 0xe4, 0x03, 0xb2, 0xd4, 0xb2, 0xfb, 0x74, 0x6e, 0x15, 0x6d, 0x74,
	0x8a, 0x96, 0x9c, 0x48, 0x8b, 0xdc, 0x47, 0xca, 0x51, 0x72, 0x82, 0xa4, 0x9a, 0x57, 0x32, 0xc9,
	0xbd, 0x92, 0x57, 0x55, 0xe2, 0x13, 0xa5, 0x93, 0x67, 0x99, 0x41, 0x96, 0x87, 0x3e, 0x5a, 0x26,
	0x85, 0x2b, 0xa1, 0xc5, 0x40, 0xe8, 0x30, 0xf0, 0x11, 0x98, 0xc2, 0xbb, 0xc1, 0x7c, 0xb9, 0x42,
	0xb4, 0xa6, 0x8a, 0xca, 0xa4, 0xb8, 0x40, 0x94, 0xc6, 0xb8, 0x36, 0x3e, 0x50, 0xc6, 0xb8, 0x32,
	0x9e, 0x02, 0x04, 0xe8, 0x45, 0x4b, 0x2e, 0x52, 0xff, 0xc6, 0xda, 0x23, 0xab, 0x29, 0x35, 0xaf,
	0xa5, 0xa2, 0x36, 0xc7, 0x69, 0x82, 0x6b, 0xeb, 0x61, 0x63, 0x7e, 0x29, 0x15, 0xb2, 0x77, 0x64,
	0x96, 0x37, 0xef, 0x93, 0x71, 0x2c, 0xe5, 0x0b, 0x44, 0xe7, 0x19, 0x1c, 0x6e, 0x11, 0x28, 0x8b,
	0xd6, 0xec, 0x33, 0x30, 0x42, 0x81, 0x71, 0xc5, 0xc2, 0xc3, 0x8a, 0x85, 0x1d, 0x4f, 0xe5, 0xe2,
	0x2c, 0x9b, 0x3b, 0xbe, 0x43, 0x2f, 0xaa, 0x17, 0xd3, 0x09, 0x4c, 0x52, 0xa9, 0x6c, 0x38, 0x38,
	0x26, 0x59, 0x91, 0xb0, 0xa4, 0xcc, 0xa0, 0x9f, 0x32, 0x7a, 0x7b, 0x3d, 0xfc, 0xae, 0x01, 0x34,
	0xd7, 0x53, 0x73, 0x64, 0xd7, 0x35, 0xea, 0xfa, 0xb0, 0xd3, 0xf4, 0x41, 0xab, 0xe9, 0x8a, 0x44,
	0x7a, 0x4d, 0x22, 0x06, 0xc3, 0x3c, 0x8d, 0x14, 0x7d, 0x0d, 0x97, 0xce, 0x4d, 0x03, 0x8d, 0xfe,
	0x06, 0x8e, 0x3a, 0x0d, 0x64, 0x30, 0x94, 0xc0, 0x11, 0x2d, 0x4c, 0x97, 0xce, 0xec, 0x00, 0x74,
	0x89, 0xeb, 0x84, 0x54, 0xf2, 0xc8, 0x1c, 0xd8, 0x23, 0xb8, 0xeb, 0xe2, 0x4d, 0x4a, 0x61, 0x2a,
	0x95, 0xaf, 0x14, 0x00, 0xce, 0xd7, 0xc0, 0x36, 0x30, 0x93, 0xa8, 0xcf, 0xba, 0xa8, 0xb3, 0x0e,
	0xea, 0xca, 0xaf, 0xc4, 0xfc, 0x2b, 0x38, 0x6d, 0xe2, 0x85, 0x17, 0x46, 0x17, 0x61, 0x12, 0xf2,
	0x6b, 0x0c, 0x76, 0x83, 0xef, 0xfc, 0xa2, 0xc3, 0xa3, 0xbb, 0x82, 0x65, 0x16, 0xff, 0x0d, 0xdf,
	0xbf, 0x34, 0x7c, 0xef, 0xe0, 0xe4, 0x39, 0x8a, 0x97, 0x84, 0xc6, 0x4f, 0x7c, 0x63, 0x7a, 0xde,
	0x7b, 0x81, 0x37, 0x33, 0xa5, 0xf7, 0xcf, 0xd4, 0xb0, 0x3d, 0x53, 0x3f, 0x0f, 0x60, 0x7f, 0xe3,
	0xe5, 0x7f, 0x32, 0x58, 0xd4, 0x9c, 0x61, 0xb3, 0xd2, 0xeb, 0x61, 0x33, 0xfa, 0x86, 0x6d, 0xd4,
	0xdf, 0xb0, 0x71, 0xef, 0xb0, 0x4d, 0xb6, 0x87, 0xcd, 0xbc, 0x67, 0xd8, 0x60, 0x6b, 0xd8, 0x5a,
	0x88, 0x4d, 0xdb, 0x88, 0x39, 0x2f, 0xe0, 0xb8, 0x0f, 0x7f, 0x39, 0x03, 0x4f, 0xba, 0x93, 0x78,
	0x5c, 0x4d, 0xe2, 0xa6, 0xb3, 0xf2, 0x3a, 0xff, 0x55, 0x07, 0xfd, 0xf5, 0x6d, 0xc4, 0xbe, 0x01,
	0xb3, 0xfe, 0xaa, 0x33, 0x6b, 0xf3, 0xd3, 0x5d, 0xf5, 0xd6, 0x3e, 0xe9, 0xb1, 0x94, 0xbf, 0x00,
	0x3f, 0xc2, 0xfe, 0xc6, 0x42, 0x66, 0x1f, 0x56, 0xde, 0xfd, 0x9f, 0x7a, 0xfb, 0x83, 0x3b, 0xed,
	0x59, 0xb4, 0x76, 0xfe, 0xc7, 0x7e, 0x80, 0xbd, 0xce, 0xae, 0x61, 0x5b, 0x01, 0x6d, 0xe2, 0xd9,
	0xf6, 0x1d, 0x56, 0x75, 0xd9, 0xaa, 0xf9, 0xe3, 0xe8, 0xee, 0x0e, 0xf6, 0xe9, 0x76, 0x5c, 0xcf,
	0x62, 0xb2, 0x3f, 0xde, 0xe5, 0xa6, 0xde, 0x79, 0x4b, 0x0b, 0x72, 0x93, 0xa1, 0x1f, 0xb5, 0x82,
	0xfb, 0xe7, 0xc6, 0x7e, 0x7c, 0x9f, 0x0b, 0xdd, 0xfd, 0xec, 0x93, 0xb7, 0xce, 0x55, 0x28, 0xae,
	0x8b, 0xcb, 0xb9, 0x9f, 0xc6, 0x8b, 0xe0, 0x9d, 0x40, 0xff, 0x7a, 0xc1, 0xc3, 0x1c, 0x93, 0x27,
	0x59, 0xca, 0xd5, 0xef, 0x37, 0xbf, 0x54, 0x7f, 0xe5, 0x5f, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x75, 0x31, 0x46, 0xd5, 0xb0, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SqlClient is the client API for Sql service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SqlClient interface {
	Transfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error)
	GetOrderHistory(ctx context.Context, in *GetOrderHistoryRequest, opts ...grpc.CallOption) (*GetOrderHistoryReply, error)
	GetOrderDeals(ctx context.Context, in *GetOrderDealsRequest, opts ...grpc.CallOption) (*GetOrderDealsReply, error)
	GetOrderDetailFinished(ctx context.Context, in *GetOrderDetailFinishedRequest, opts ...grpc.CallOption) (*GetOrderDetailFinishedReply, error)
	GetMarketUserDeals(ctx context.Context, in *GetMarketUserDealsRequest, opts ...grpc.CallOption) (*GetMarketUserDealsReply, error)
}

type sqlClient struct {
	cc *grpc.ClientConn
}

func NewSqlClient(cc *grpc.ClientConn) SqlClient {
	return &sqlClient{cc}
}

func (c *sqlClient) Transfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error) {
	out := new(TransfersResponse)
	err := c.cc.Invoke(ctx, "/protos.Sql/Transfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlClient) GetOrderHistory(ctx context.Context, in *GetOrderHistoryRequest, opts ...grpc.CallOption) (*GetOrderHistoryReply, error) {
	out := new(GetOrderHistoryReply)
	err := c.cc.Invoke(ctx, "/protos.Sql/GetOrderHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlClient) GetOrderDeals(ctx context.Context, in *GetOrderDealsRequest, opts ...grpc.CallOption) (*GetOrderDealsReply, error) {
	out := new(GetOrderDealsReply)
	err := c.cc.Invoke(ctx, "/protos.Sql/GetOrderDeals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlClient) GetOrderDetailFinished(ctx context.Context, in *GetOrderDetailFinishedRequest, opts ...grpc.CallOption) (*GetOrderDetailFinishedReply, error) {
	out := new(GetOrderDetailFinishedReply)
	err := c.cc.Invoke(ctx, "/protos.Sql/GetOrderDetailFinished", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlClient) GetMarketUserDeals(ctx context.Context, in *GetMarketUserDealsRequest, opts ...grpc.CallOption) (*GetMarketUserDealsReply, error) {
	out := new(GetMarketUserDealsReply)
	err := c.cc.Invoke(ctx, "/protos.Sql/GetMarketUserDeals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqlServer is the server API for Sql service.
type SqlServer interface {
	Transfers(context.Context, *TransfersRequest) (*TransfersResponse, error)
	GetOrderHistory(context.Context, *GetOrderHistoryRequest) (*GetOrderHistoryReply, error)
	GetOrderDeals(context.Context, *GetOrderDealsRequest) (*GetOrderDealsReply, error)
	GetOrderDetailFinished(context.Context, *GetOrderDetailFinishedRequest) (*GetOrderDetailFinishedReply, error)
	GetMarketUserDeals(context.Context, *GetMarketUserDealsRequest) (*GetMarketUserDealsReply, error)
}

func RegisterSqlServer(s *grpc.Server, srv SqlServer) {
	s.RegisterService(&_Sql_serviceDesc, srv)
}

func _Sql_Transfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).Transfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sql/Transfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).Transfers(ctx, req.(*TransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sql_GetOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).GetOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sql/GetOrderHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).GetOrderHistory(ctx, req.(*GetOrderHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sql_GetOrderDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).GetOrderDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sql/GetOrderDeals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).GetOrderDeals(ctx, req.(*GetOrderDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sql_GetOrderDetailFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderDetailFinishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).GetOrderDetailFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sql/GetOrderDetailFinished",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).GetOrderDetailFinished(ctx, req.(*GetOrderDetailFinishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sql_GetMarketUserDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketUserDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).GetMarketUserDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Sql/GetMarketUserDeals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).GetMarketUserDeals(ctx, req.(*GetMarketUserDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sql_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Sql",
	HandlerType: (*SqlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfers",
			Handler:    _Sql_Transfers_Handler,
		},
		{
			MethodName: "GetOrderHistory",
			Handler:    _Sql_GetOrderHistory_Handler,
		},
		{
			MethodName: "GetOrderDeals",
			Handler:    _Sql_GetOrderDeals_Handler,
		},
		{
			MethodName: "GetOrderDetailFinished",
			Handler:    _Sql_GetOrderDetailFinished_Handler,
		},
		{
			MethodName: "GetMarketUserDeals",
			Handler:    _Sql_GetMarketUserDeals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/sql.proto",
}
